### ISSUE TITLE
Adjust Server Transform Parameters on a Per-Doc Basis with DM SDK.

### ISSUE THREAD

**Issue by ryanjdew** [marklogic/java-client-api#1039]
I'd like to use the WriteBatcher in DM SDK with a transform with a variety of transform options. Some options in my transform are document-dependent, so I would like the ability to set the option on a per-document basis.

A feature request for the MarkLogic NiFi Bundle would rely on this enhancement. See https://github.com/marklogic/nifi/issues/13 

### Version of MarkLogic Java Client API
MarkLogic 4.1.1

### Version of MarkLogic Server

9.0-7.2

### Java version

1.8.0_77

### OS and version

MacOS 10.14.2

**Comment by jmakeig** [comment]
@ryanjdew, I don’t quite understand your use case. Isn't it generally the case that you‘d want to handle a batch of things the same? How would you even configure per-document transformations in NiFi? Wouldn’t the dispatching to specific transformation logic make more sense in the transformation code in MarkLogic? That way it could look at the data itself as well to decide how to transform it. 

Maybe I’m missing your point, though. Any other details would be much appreciated.

**Comment by ryanjdew** [comment]
Each FlowFile that comes into the PutMarkLogic processor results in a document that gets written to MarkLogic. In NiFi you could funnel multiple sources into a common flow. If we could read each FlowFile for attributes that indicate the original source before entering the funnel, we could pass the source into a transform parameter (or in the case of DHF, as a value in 'trans:options') to track lineage.

We could work around it now by having a completely separate flow per source, but keeping things DRY is always nice.

**Comment by ehennum** [comment]
@ryanjdew , doesn't the NiFi processor use DMSDK.  DMSDK reads and writes batches of documents.  To apply a different transforms to different documents within a batch would require a change to the REST API, that's certainly possible, but we've had the request to process each batch of documents with a single transform call.
Wouldn't it be typical to apply different transformations within NiFi to different data sources?  Product rows and customer rows presumably require different transformations.  Transformations that can be done in isolation without the database indexes are probably best done outside the database to minimize load on the transactional component of the system.

**Comment by jmakeig** [comment]
> Each FlowFile that comes into the PutMarkLogic processor results in a document that gets written to MarkLogic.

I don’t understand what that means. Can you help translate from NiFi-ese? (Your patience is appreciated.) The point of DMSDK is to _not_ do things one document at a time. Batching allows for significant performance advantages, such as splitting and parallelizing large jobs. However, batching assumes some uniformity in how you handle the whole set in order to do some of those optimizations.

Adding @yasht2010 too.

**Comment by ehennum** [comment]
Could the NiFi processor take the attributes and construct the envelope pattern documents before sending them to the server? 
Again, if the work doesn't have to be done on the server, it's better to do the work on the client, especially if that work is motivated by the idioms of the framework.

**Comment by ryanjdew** [comment]
NiFi isn't great at document construction. Perhaps the best route will be to encourage the process of storing that information as properties or metadata on ingest and insert it into a header at the time of harmonization to avoid cross fragment searches with content in data-hub-FINAL.

**Comment by ehennum** [comment]
Instead of putting the document construction in NiFi proper, could the document construction exist in the processor that bridges between NiFi and DMSDK?

**Comment by jmakeig** [comment]
As @ehennum indicates, if the transformation/re-structuring does not require MarkLogic indexes, we should aggressively push this to external tools. Couldn’t we have a Data Hub processor that knows how to assemble envelopes and DHF-specific metadata? If so, what lands in the staging database would be ready to harmonize without needing any additional physical transformation in the E-node. Thus anything that could land data in this format could participate in harmonization without any changes to the hub. A standard staging format would allow us to decouple ingest from harmonization, removing the need for input flows, except in the case that the input transformation needs to happen in the hub, for example, to lookup information from indexes.

What am I missing/misinterpreting?

**Comment by ryanjdew** [comment]
I'm not sure that anything is really being misinterpreted. It is simply a question of where the most friction is and it sounds like it is with the REST API/Java Client API, so we should take care of it on the NiFi side. 

We could do some basic envelope construction in a NiFi processor instead of through the DHF ingest. It does break from the typical DHF pattern of building an ingest flow and referencing that to transform. It would be more of a generic "PutEnvelopeMarkLogic" or something since it wouldn't directly interact with DHF. It would just wrap existing data in an envelope. Either way, those are details for us to figure out on our end.

**Comment by yasht2010** [comment]
Hello everyone. Please forgive my naivety on this matter. 

I know we talk about "Load as-is" quite a bit. When I read this as an external developer, I interpret this as - "Let me throw any JSON and XML document and MarkLogic will figure out the rest of the format conversion". I believe input flows in DHF does this job - throw a JSON/XML document and it lands into staging in the format appropriate for DHF. I don't think external developers have a preference for envelope format. 

Hence, wouldn't my response to that as an external developer be? - 

_MarkLogic should abstract away those details from me. Isn't this what "Load as-is" is all about? Why should I care about MarkLogic Indexes? I just need this document to be ingested into MarkLogic Data Hub_ 

The precedent we are setting here is that tomorrow if a customer wants to create a processor for another 3rd party tool (Mulesoft, StreamSets, Confluent...etc), they will need to know the envelope format and what format MarkLogic Data Hub accepts and what it doesn't. I just want everyone to be cognizant of the precedent we are setting here and how it changes the perception of "load as-is".  

We can go ahead exactly as Ryan suggests, break the typical DHF pattern and build a "MarkLogicDHFIngest" processor which does the envelope format conversion. But if we change the envelope format tomorrow, our processor would be rendered useless.

**Comment by jmakeig** [comment]
> the typical DHF pattern of building an ingest flow and referencing that to transform

Right. The default today in DHF is to ingest into an input flow. That input flow takes raw data and readies it for harmonization, wrapping it in an envelope, adding metadata, applying permissions, sticking it in the right collections, etc. This is good in that it encapsulates the DHF aspects. “You just point your raw data ingest to this specific pipe and I‘ll do all of the prep work for you.” That does mean that ingest clients have to know about DHF and how to interact with an input flow, MarkLogic has to do a little more work, and you have to get a MarkLogic developer to implement the staging logic, rather than a Java developer.

The alternative is to say, “Here’s how the data should look after being staged. As long as you can prepare your data to look like that, you can load it in whatever manner you choose.” This is good in that clients can use any available means to load data. However, it puts more of a burden on the client to implement the staging contract, losing the benefits of the encapsulation in the input flow.

**Comment by jmakeig** [comment]
> MarkLogic should abstract away those details from me. Isn't this what "Load as-is" is all about?

Agreed, but that abstraction could happen at the NiFi processor level. Instead of a generic `PutMarkLogic` processor, `PutDataHubStaging`, as you suggest. (That’s still “Load as-is” from the customer’s perspective.) If we can fully automate all of the preparation (envelope, provenance, metadata), it would make sense to encapsulate this in a DHF endpoint, so clients don’t have to implement this themselves. Is a custom input flow the corner case and we should be able to fully encapsulate staging logic behind a generic ingest endpoint?

**Comment by yasht2010** [comment]
"Is a custom input flow the corner case and we should be able to fully encapsulate staging logic behind a generic ingest endpoint?"

I don't have user data to answer this question. I'll try to speak to a couple of consultants or customers and see if it there is a pattern here.

**Comment by ehennum** [comment]
This issue can be reopened later if needed.
