### ISSUE TITLE
SPARQLQueryManager.executeAsk() results in NullPointerException

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic/java-client-api#1074]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
4.1.1

### Version of MarkLogic Server

9.0-7.2
### Java version
Open JDCK 10.0.2 compiling for version 1.8
Run `java -version`

### OS and version
linux

I just ran into what looks like a bug in the marklogic-client-api-4.1.1 code.
When trying to execute a SPARQL ASK query, I get a NullPointerException on line 160 of SPARQLQueryManagerImpl:
(158) Boolean executeAsk(SPARQLQueryDefinition qdef, Transaction tx) {
(159)     JsonNode result = executeQueryImpl(qdef, new JacksonHandle(), tx, false).get();
(160)     return result.get(“boolean”).asBoolean();
(161) }
 
When I step through in the debugger, it appears that line 159 executes correctly and returns a BooleanNode.
But the BooleanNode doesn’t have a child value of “boolean”, or any children at all, just it’s Boolean value.
So the get clause in line 160 returns null and the whole thing fails.
I think line 160 should read:
  return result.asBoolean();

**Comment by ehennum** [comment]
@tdiepenbrock , I'm wondering if the problem is in the response from the server.

I modified this unit test to run with and without a transaction:

com.marklogic.client.test.SPARQLManagerTest#issue_357

It ran without issues. In addition, it looks like asBoolean() is supported by BooleanNode:

https://fasterxml.github.io/jackson-databind/javadoc/2.0.0/com/fasterxml/jackson/databind/node/BooleanNode.html#asBoolean()

One potential cause for the NPE would be if the response is missing a "boolean" key.

Can you print out the JSON response from the server?

**Comment by ehennum** [comment]
Noting that the discrepancy appears in the output from the REST API, which returns a single true | false value in Tom's environment but {"head":{},"boolean":true} in my environment.

The REST API XQuery modules and the Java API classes for the SPARQL ask request don't appear to have changed significantly for at least a year. I suppose the cause could be a change in the sparql-results-json serialization.

**Comment by ehennum** [comment]
We've determined that customization of the REST API server is the probable root cause.
