### ISSUE TITLE
Few Methods of the class com.marklogic.client.query.StructuredQueryBuilder should return StructuredQueryDefinition

### ISSUE THREAD

**Issue by sowmyapap** [marklogic/java-client-api#1117]
The methods such as collection​(), directory() etc of the class "StructuredQueryBuilder" should have a return type of "StructuredQueryDefinition" similar to the other query constructors.

The current behavior is that it returns the type "StructuredQueryBuilder.CollectionQuery" leading to compile time errors due to visibility issue.

**Comment by ehennum** [comment]
I don't think it is accurate to say that there is a compile time issue. Instead, there is a usability issue.
Because StructuredQueryBuilder.CollectionQuery derives from StructuredQueryDefinition and because StructuredQueryDefinition is public, applications can already assign the return value of collection() to a StructuredQueryDefinition variable.
However, that is certainly not intuitive.

**Comment by ehennum** [comment]
Should cause no regressions because the protected derived interfaces couldn't be used anyway.

**Comment by georgeajit** [comment]
No regressions seen. Verified on 08/21/2019 Jenkins test results.
