### ISSUE TITLE
WriteBatcher fails with SVC-EXTIME when transmitting large xml-files (~85MB)

### ISSUE THREAD

**Issue by ralfhergert** [marklogic/java-client-api#1222]
In our application we have to deal with bulk-ingest-jobs of roughly 1.3 Mio documents. Each job requires a manifest.xml-file specifing all changes to be applied to the documents (update or removal). The manifest-xml file has a size of ~85MB.

We are trying to use the WriteBatcher to transmit all files including the manifest.xml into the MarkLogic DB. And it appears that the App Server Default Time Limit of 600s does not suffice to transmit the 85MB large file. Is there a way to improve the performance?

We are running the MarkLogic server on three nodes. It appears that using only a single-node-setup the performance is better and the timeout is much less likely to ocurr.

### Version of MarkLogic Java Client API
5.1.0

### Version of MarkLogic Server
9.0-7.2 (running on three nodes)

### Java version
openjdk 11.0.4 2019-07-16

### OS and version
adoptopenjdk/openjdk11:jre-11.0.4_11-alpine

### Actual output: What did you observe? What errors did you see? Can you attach the logs?
The WriteBatcher thorws the following error:
> failed to apply resource at documents: Internal Server Error. Server Message: SVC-EXTIME: Time limit exceeded . See the MarkLogic server error log for further detail.

There is no corresponding message in the server log.

### Expected output: What specifically did you expect to happen?
Both client and server are in the same lokal network. There is no internet involved. The transmission of large files should be possible and also faster.

**Comment by ehennum** [comment]
@ralfhergert , the general recommendation for modeling in MarkLogic is to put each record in a separate document. (From a relational lens, one row per document instead of one table per document.)  That approach yields the optimal granularity for update, indexing, and retrieval.

If I understand correctly, you're taking that modelling approach in general, and the manifest document is an outlier.

WriteBatcher is beneficial for ingesting many records but doesn't have any benefit for writing a single large document.

One approach would be to use a DocumentManager to write the manifest document after the job for the records ends.  Do you still see the timeout if you take that approach?

**Comment by ralfhergert** [comment]
In general we follow the approach that different records should be different documents. For our bulk-ingestion-jobs we first transmit all the documents and finally the manifest.xml. In which the purpose of the manifest.xml is twofold:
 * the manifest.xml being written will trigger our server-side validation and post-processing of all the documents included in the bulk-ingest and therefor
 * the manifest.xml serves as kind of an inventory list.

Thank you for the hint towards the DocumentManager. I'll try using DocumentManager.patch() to transmit the manifest.xml in chunks. I'll come back with some results...

**Comment by ehennum** [comment]
Hi, @ralfhergert - I'd suggest trying DocumentManager.write() on the grounds that the document might be small enough to insert in a single transaction that's not part of a larger batch.

One alternative:  break the manifest into several documents, write each manifest part separately into a manifest-specific directory or collection, and trigger the validation and post-processing either incrementally on each manifest part or on the last part as appropriate.  Is that a possibility?

**Comment by ralfhergert** [comment]
Thanks for your advice @ehennum. When using the WriteBatcher we tried to transmit the manifest.xml in its own batch by isolating it with WriteBatcher.flushAndWait() before and after. When using DocumentManager.write() instead to transmit this file the performance characteristics seem to be the same.
My tests with DocumentManager.patch() were unsuccessful, because the more elements an xml file has, the longer the patch-operations need. The time necessary grows in a quadratic manner (O(n²)).
That means splitting the large file into multiple documents might be indeed the best option.

@ehennum, would our large file be a problem for MLCP? We did use the MLCP before and I can not remember of any timeouts happening due to large documents there. MLCP uses XMDP instead of the REST-API. I understood that large documents should in general be a problem for the MarkLogic DB and I would expect both interfaces XMDP and REST-API to be affected in the same way. What is different with MLCP using XMDP over the REST-API?

**Comment by ehennum** [comment]
@ralfhergert , to clarify, I was suggesting DocumentManager.write() because the Java API can optimize transport of a single document without metadata as a streaming payload instead of having to use a multipart payload (as is necessary with batches of documents or a document and metadata).

Anyway, I should have checked first -- does the error log show which operation is timing out?

https://docs.marklogic.com/messages/SVC-en/SVC-EXTIME

XDBC is a lower-level interface and might or might not be able to finish a write that's near timeout limits.

The other alternative that occurs to me is to write and install a Data Service endpoint that takes a single document as input:

http://docs.marklogic.com/guide/java/DataServices

Even if that approach worked for a while, the workaround might bump up against a limit later.  For that reason, incremental finalization on multiple manifests in a directory seems like a more scalable long term solution (if refactoring is possible).
