### ISSUE TITLE
splitWriteOperations​ method's second parameter could have a better name than inputName

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1237]
### Version of MarkLogic Java Client API
develop (post 5.2.0 release)
### Version of MarkLogic Server

10.0 nightly release (post 10.0-4 release)

### Java version

Open jdk 8 or 9

### OS and version

Windows /  IDE

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

```splitWriteOperations​(java.io.InputStream input, java.lang.String inputName)```

### Actual output: 
```inputName``` parameter name does not convey the fact that a filename (as a template name for individual line URIs)  is required.

### Expected output: What specifically did you expect to happen?
N/A
### Alternatives: What else have you tried, actual/expected?
N/A

**Comment by ehennum** [comment]
@georgeajit and @llinggit , how about inputFilename as the parameter name?

**Comment by llinggit** [comment]
I think this parameter means more to the extracted file names. We use this name and sometimes the extension of this parameter to construct the output file names. Because this could be different from the input file's name, that's why I think inputName is a little confusing, but I don't have a better name. inputFilename is kind of similar to inputName I think.

**Comment by ehennum** [comment]
Good point.  How about splitFilename on the principle that we're splitting both the input and the filename?

**Comment by llinggit** [comment]
I think this is much better. How about it @georgeajit ?

**Comment by georgeajit** [comment]
That name along with associated Java Docs support will be fine.

**Comment by georgeajit** [comment]
Test corrected to have new names.
