### ISSUE TITLE
Clear collections is not working in Java API

### ISSUE THREAD

**Issue by shivling1254** [marklogic/java-client-api#1256]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
Java API v4.1.0

### Version of MarkLogic Server
MarkLogic v10

### Java version
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

### OS and version
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19041 N/A Build 19041

### Input:
I am using MarkLogic v10 and Java API v4.1.0. My requirement is to clear collections from the specific document,

I am using the below code snippet to clear all the collections,

```
XMLDocumentManager xmlDocumentManager = client.newXMLDocumentManager();

DocumentMetadataHandle metadataHandle = new DocumentMetadataHandle();
xmlDocumentManager.readMetadata("/test/inventory", metadataHandle);

DOMHandle domHandle = new DOMHandle();
xmlDocumentManager.read("/test/inventory", domHandle);

metadataHandle.getCollections().clear();
xmlDocumentManager.write("/test/inventory", metadataHandle, domHandle);
```
I already posted question on StackOverflow :
[https://stackoverflow.com/questions/63734972/clear-collections-is-not-working-in-java-api](url)

### Expected output: 
After running the above snippet, it should remove all the collections from the document but it is not happening.

**Comment by ehennum** [comment]
Thanks for the follow up with the bug.

Clear collections only clears locally for the in-memory DocumentMetadataHandle in the Java API client of the REST API.

The behavior of the REST API invoked by the Java API depends on the configuration of the update policy of the REST API server:

- MERGE_METADATA preserves the current metadata of an existing document for any metadata category that's not sent by the client.
- OVERWRITE_METADATA ignores the current metadata of an existing document

Changing the update policy to OVERWRITE_METADATA should yield the expected behavior.

Here's the Java API code for making that change:

```
        ServerConfigurationManager configMgr = client.newServerConfigManager();
        configMgr.readConfiguration();
        configMgr.setUpdatePolicy(ServerConfigurationManager.UpdatePolicy.OVERWRITE_METADATA);
        configMgr.writeConfiguration();
```

Note that 

- The server configuration will remain in effect until changed.  Typically, the configuration is never changed after setting.
- In recent releases of the MarkLogic server, the default update policy changed from MERGE_METADATA to OVERWRITE_METADATA 

I'll provide this comment in StackOverflow as well in case other developers run into the issue.

All that said, the Java API is missing a client interface to make the REST API request to reset metadata on existing documents to defaults along the lines of

void DocumentManager.resetMetadata(DocumentManager.Metadata category, java.lang.String... uris);

The default for collections is none unless the role has been configured to have a default collection, in which case the administrator's configuration takes precedence over the client's request.

**Comment by ehennum** [comment]
@shivling1254, does changing the update policy to OVERWRITE_METADATA on the REST API server (as described in the previous comment) make it possible to set the metadata correctly on documents?

**Comment by shivling1254** [comment]
It is working as expected after changing the update policy to OVERWRITE_METADATA.

Thank you @ehennum

**Comment by ehennum** [comment]
Thanks for confirming, @shivling1254 

The Java API should still expose resetMetadata(), so I'll keep this ticket open for that task.

**Comment by ehennum** [comment]
For consistency with the existing DocumentManager methods, the new methods should have the following name and signatures: 

```
    void writeDefaultMetadata(String... uris)
    void writeDefaultMetadata(Transaction transaction, String... uris);
```

**Comment by ehennum** [comment]
See comment above about the new writeDefaultMetadata() methods.  

Please consider whether the unit test provides sufficient coverage, given that the method merely adds the category parameter to a request that's already supported.

**Comment by georgeajit** [comment]
I think a sanity test with other overload method can be added to QA tests.

**Comment by georgeajit** [comment]
Can we have better error message when a call such as ```docMgr.writeDefaultMetadata();``` is made? Currently error response is
```Local message: failed to delete resource at documents: Bad Request. Server Message: REST-REQUIREDPARAM: (err:FOER0000) Required parameter: uri```

**Comment by ehennum** [comment]
Empty var args should be caught on the client now.
