### ISSUE TITLE
Question - Are there any plans to write a reactive/non-blocking client API?

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/java-client-api#1281]
I was wondering if MarkLogic has a plan to write something similar to reactive stream API? I could go over REST using a library like Spring WebFlux to get non-blocking behavior. But I'm more interested to know if you could support something like Mongo change stream? (https://developer.mongodb.com/quickstart/java-change-streams) I wanted to listen for changes in a collection from outside the MarkLogic server. The change stream should be pushed to the client over HTTP.  Change stream would be helpful if the applications deployed outside the MarkLogic server wanted to get notification about the mutations in a given collection or database. Do we have a way to do that using the existing MarkLogic ecosystem?

**Comment by ehennum** [comment]
Hi, Sanju:

Thanks for the inquiry.

MarkLogic provides ACID transactions such that, if the call from the client returns without throwing an exception, the client knows immediately that the request committed successfully without having to poll or wait for notification.

The MarkLogic Java API provides DMSDK (the Data Movement SDK) to support asynchronous jobs where the job queues data to write, dispatches data after read, and dispatches notifications of changes and errors.  

A Java application can also poll for changes by querying for changes since the last update to a timestamp document.

Hoping that's useful,

**Comment by sanjuthomas** [comment]
@ehennum, Thank You! I'm aware of the capabilities mentioned in the response.
