### ISSUE TITLE
Publish Java Client API release on github

### ISSUE THREAD

**Issue by nikos** [marklogic/java-client-api#253]
This ticket relates to #147 but scopes it to a simple publication of the JAR+POM file as part of this very git repository "java-client-api".

Then you could refer to the repository from your gradle file like:

    maven { url "http://marklogic.github.io/java-client-api/releases" }

As an example where this is also used, see ml-gradle plugin from Rob (https://github.com/rjrudin/marklogic-java/blob/master/sample-project/build.gradle on how to leverage it).

For deployment/upload of the JAR artefact there seems to be a handy github-maven plugin available from: https://github.com/github/maven-plugins (source: http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github)

**Comment by nikos** [comment]
Actually it turns out, that an older version 3.0.0-EA3 is available via 

    maven { url "https://raw.github.com/marklogic/java-client-api/mvn-repo" }

Hopefully the 3.0.1 will be turning up there also soon :)

**Comment by sammefford** [comment]
We were thinking that since 3.0.1 will be going to Maven Central, there would be no benefit to also hosting it in github.  Since Maven Central is a default repo for maven and gradle, even less configuration is required to use our binaries from there.  You should only need:
``` xml
<dependency>
    <groupId>com.marklogic</groupId>
    <artifactId>java-client-api</artifactId>
    <version>3.0.1</version>
</dependency>
```

Please help me understand if we're missing something.  Also, since the [mvn-repo builds](https://github.com/marklogic/java-client-api/tree/mvn-repo/com/marklogic/client-api-java) add significantly to the size of each clone, there's some advantage to removing the EA versions currently available in our mvn-repo.  

What do you think?  Is there any reason for us to keep the old EA releases in mvn-repo once the final GA release is in Maven Central?  Is there a reason to publish GA builds to github mvn-repo once they're on Maven Central?

**Comment by nikos** [comment]
If the Java Client API 3.0.1 (and subsequent releases) will be available (soon :) on Maven Central this would be fantastic (older EA releases are fine to be available through github repo URL). Personally I would really ensure, that:
* the artefact is available on Maven central as soon the build has been finished and declared ready for release
* the coordinates (in maven and gradle format) for accessing the Java Client API is part of the start page / README.md

**Comment by sammefford** [comment]
The Java Client API 3.0.1 is available on maven central: http://repo1.maven.org/maven2/com/marklogic/java-client-api/3.0.1/ .  You can include it in your project using the dependency section from my last comment.  I'll add the coordinates in maven and gradle format to README.md shortly.  Thanks again for the great suggestions.
