### ISSUE TITLE
Query test future search failed reported in Stress test client logs

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#260]
On a Stress Test environment with MarkLogic 0218 build, as soon as stress client is started, we have Errors reported on query test search. Based on conversation with Sam, this issue is being reported with script logs.

14:58:58 About to load 2501 documents.
14:59:01 Querying...
14:59:01 Querying...
14:59:02 Querying...
14:59:02 Querying...
ERROR query test future search failed (collection: /KWFXEIYJVPZIOGIF/2015118145857922/13/0/0/) expected 101 contained -1
Exiting...
ERROR query test future search failed (collection: /KDTJNMSLHIWCINQX/2015118145857923/19/0/0/) expected 119 contained -1
Exiting...
ERROR query test future search failed (collection: /CIKBCQMUOLJFBUTT/2015118145857922/1/0/0/) expected 109 contained -1
Exiting...
ERROR query test future search failed (collection: /GWUYUKXFHITBHLAV/2015118145857923/7/0/0/) expected 115 contained -1
Exiting...
ERROR query test key-value search failed (collection: /KDTJNMSLHIWCINQX/2015118145857923/19/0/0/) expected 119 contained -1
Exiting...
ERROR query test key-value search failed (collection: /CIKBCQMUOLJFBUTT/2015118145857922/1/0/0/) expected 109 contained -1
Exiting...
ERROR query test key-value search failed (collection: /KWFXEIYJVPZIOGIF/2015118145857922/13/0/0/) expected 101 contained -1
Exiting...
ERROR query test key-value search failed (collection: /GWUYUKXFHITBHLAV/2015118145857923/7/0/0/) expected 115 contained -1
Exiting...
14:59:03 Average: 3

**Comment by sammefford** [comment]
I can't duplicate this locally using build 7.0-20150220.  So I need to figure out what's different about your env vs mine.  I'm guessing it's not just because you're running a cluster and I'm running a single node.  So far I see no smoking gun in the java output log file, nor in the folders with the stress test code & config.  It looks like you got the latest version of the java client api jar (2015/02/18), which is good.

**Comment by sammefford** [comment]
I have duplicated this and I believe it's happening for the same reason as #259: This is because to improve Search API performance some changes from 8 were back-ported to 7 which conditionally skip estimating the total, and as part of that do not return the total attribute.

The fix is already in the 7.0 & 8.0 branches.  We just need to decide now whether it will be included in the 7.0-5 release.

**Comment by sammefford** [comment]
Sorry, I said that wrong.  The fix is on trunk & b8_0 branches, not yet on b7_0.  We need to decide whether it will be included in the 7.0-5 release.

**Comment by georgeajit** [comment]
Tested on 0225 ML Build and found that the issue is fixed.
