### ISSUE TITLE
Document connection pooling behavior and configuration

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#301]
How does connection pooling work? What are its defaults? What are the levers available to modify its behavior?

**Comment by kcoleman-marklogic** [comment]
Pushing out since I have no info with which to fulfill this task. I have a query out to Sam and Erik, and will pull it back in to 8.0-4 if I can get what I need in time.

**Comment by kcoleman-marklogic** [comment]
I added a one-liner in 8.0-5 to the effect that we use HttpClient for connection pooling. Since I have not been able to get any more detailed information than that from the devs, that's all I'm planning to say.

Is that sufficient to address your needs, Justin? If not, please reassign to Sam.

**Comment by sammefford** [comment]
Sorry, Kim, that this missed my radar.  It's assigned to me now, so I'll get you something during EA4.

**Comment by sammefford** [comment]
Due to bug load right now, I need to push this to 4.0.1

**Comment by sammefford** [comment]
Each time you call DatabaseClientFactory.newClient you create a new DatabaseClient instance which is associated 1-1 with a connection pool.  The connection pool makes efficient reuse of connections and therefore a DatabaseClient instance should be reused as much as possible throughout the life of an application rather than used, discarded, then re-created.  After initial configuration the DatabaseClient instance is thread-safe (it can be reused across many threads).  The connection pool is configured to have 100 connections.  This means the maximum number of HTTP socket connections per DatabaseClient is 100.  Each DatabaseClient is only pointed to one combination of host, port, database, and security configuration.  If an application needs to create additional DatabaseClient instances (because it needs to connect with multiple hosts or ports or databases or users) keep in mind that a separate connection pool will be associated with each DatabaseClient instance.  

When any call to the Java Client API makes a new request to the MarkLogic server, an available connection is drawn from the pool and used for the HTTP request.  When the HTTP response is received, processed, and closed, the connection is made available again to the connection pool.  No state information is maintained with the connection.  All cookies are discarded unless a Transaction is in use, in which case the cookies are associated with the transaction, not the connection.

As of 4.0.0 the connection pool can only be adjusted by implementing HttpClientConfigurator and doing any adjustment in the configure method.  However, it should be noted that HttpClient will likely be replaced in a future version and thereafter this ClientConfigurator will be ignored.

**Comment by sammefford** [comment]
@jmakeig please take a look and provide me any feedback.

**Comment by sammefford** [comment]
Kim, I'm assuming that when Justin marked it "ship" he means he reviewed and it's ok as is and he has nothing to add.  Please reach out to me when you're ready to work on this if you need help fitting in what we already have.

**Comment by kcoleman-marklogic** [comment]
A topic on connection management and configuration has been added to the dev, under the discussion of DatabaseClient, and reviewed by Sam. All revisions are in, so I think this is good to go for 4.0-1/9.0-1.

**Comment by sammefford** [comment]
The new sections are titled "Expected Client Lifetime" and "Connection Management and Configuration".
