### ISSUE TITLE
"Not a native Java type" with path range index on array

### ISSUE THREAD

**Issue by malteseduck** [marklogic/java-client-api#383]
For this JSON structure: 

```
{
  "topics": [
    "fishes",
    "wishes"
  ]
}
```

and having this path range index:

```
/topics
```

and this POJO with this property/getter/setter:

```
private List<String> topics;

@PathIndexProperty(scalarType = PathIndexProperty.ScalarType.STRING)
public List<String> getTopics() {
    return topics;
}

public void setTopics(List<String> topics) {
    this.topics = topics;
}
```

and this query (using `PojoQueryBuilder`):

```
qb.range("topics", Operator.EQ, "fishes"),
```

I get this error:

```
java.lang.IllegalArgumentException: Property topics is not a native Java type
    at com.marklogic.client.impl.PojoQueryBuilderImpl.getRangeIndexType(PojoQueryBuilderImpl.java:250)
    at com.marklogic.client.impl.PojoQueryBuilderImpl.range(PojoQueryBuilderImpl.java:90)
    at lds.cs.ws.training.TrainingRepository.facetedSearch(TrainingRepository.java:95)
```

Looking at that code I can see why since it is a `List` and that doesn't match any of the options.  In QConsole if I do this query (in XQuery):

```
cts:search(
  fn:collection(),
  cts:path-range-query("/topics", "=", "scary")
)
```

I get results, but obviously there are no types involved there so woohoo for me.  It works if I do this a `StructuredQueryBuilder` instead:

```
qb.range(qb.pathIndex("/topics"), "xs:string", StructuredQueryBuilder.Operator.EQ, topic)
```

Is that the only way?  Should the `PojoQueryBuilder` need to handle this case in some way?  I am fine using the `StructuredQueryBuilder` approach but just wanted to make sure there wasn't an "easier" way and to check whether or not there _should_ be an "easier" way

Thanks.

**Comment by sammefford** [comment]
The POJO Data Binding Interface is Java-first.  This means it is only intended to work with data created from within the POJO Data Binding Interface, which your JSON document is not.  Are you able to create the documents from Java?

**Comment by malteseduck** [comment]
We were, but on the Jackson ObjectMapper we omitted `JsonTypeInfo.As.WRAPPER_OBJECT` so the object was not wrapped.  I threw together a more "vanilla" example (sorry, should have done that in the first place) to see if the issue went away and now my JSON looks like this:
```
{
  "lds.stack.examples.marklogic.model.Training": {
    "id": "21f349b6-89ee-4bef-8b04-d4a655452114", 
    "topics": {
      "java.util.ArrayList": [
        "wishes", 
        "fishes"
      ]
    }
  }
}
```
I expected the root wrapper, but not the one inside of `topics`.  Is that what it is supposed to do?  I tried to find examples or warnings about using `List` for the data type but have been unable to find any (not saying they don't exist). 

I still get the same exception that I got with my previous example, but now none of the other methods I tried work either (probably because the path index is not "complete" so there are no values).  Here is the exception:
```
java.lang.IllegalArgumentException: Property topics is not a native Java type
	at com.marklogic.client.impl.PojoQueryBuilderImpl.getRangeIndexType(PojoQueryBuilderImpl.java:250)
	at com.marklogic.client.impl.PojoQueryBuilderImpl.range(PojoQueryBuilderImpl.java:90)
	at lds.stack.examples.marklogic.PojoRepositoryTest.testPojoRepositoryPathRange(PojoRepositoryTest.java:50)	
```
and here is my new index:
```
{
      "path-expression" : "lds.stack.examples.marklogic.model.Training/topics",
      "scalar-type" : "string",
      "collation" : "http://marklogic.com/collation/",
      "range-value-positions" : "false",
      "invalid-values" : "ignore"
    }
```
Here is the full model:
```
public class Training implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    private String id;
    private List<String> topics;

    public Training() {
        this.id = UUID.randomUUID().toString();
    }

    public Training(List<String> topics) {
        this();
        this.topics = topics;
    }

    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @PathIndexProperty(scalarType = PathIndexProperty.ScalarType.STRING)
    public List<String> getTopics() {
        return topics;
    }

    public void setTopics(List<String> topics) {
        this.topics = topics;
    }
}
```
and the query code:
```
PojoRepository<Training, String> repo = clients.first().newPojoRepository(Training.class, String.class);
PojoQueryBuilder<Training> qb = repo.getQueryBuilder();

Training training = new Training(Arrays.asList("wishes", "fishes"));

repo.write(training);

PojoPage page = repo.search(qb.range("topics", PojoQueryBuilder.Operator.EQ, "scary"), 0);
page.forEach(System.out::println);
```
What am I doing wrong?

**Comment by kcoleman-marklogic** [comment]
I think the problem you're having is that List<String> is (obviously) not a scalar type. AFAIK, the annotation is not meant for anything except a property with scalar type.

We'll have to see what Sam has to say as he is far more knowledgeable about this than I am, but I don't think you'll be able to use the index configuration generator at all for this construct. Rather, you'll need to examine the generated JSON and construct an appropriate path index definition on your own. 

In this case, I expect the path expression would be something like ```/lds.stack.examples.marklogic.model.Training/topics/java.util.ArrayList```. The value nodes for items in a JSON array have the enclosing property name for their node name, so that actually refers to the string values in the array, believe it or not.

Have you tried that already and found it not to work?

**Comment by sammefford** [comment]
I see what's happening now.  Thanks for taking the time to spell this out.  It looks as though we currently only support scalar types for range indexes.  But since you've demonstrated how to do what you want using StructuredQueryBuilder, I'm sure we can add support to PojoQueryBuilder.

For now i think the work-around is to use JacksonDatabindHandle or JacksonHandle and StructuredQueryBuilder.

**Comment by sammefford** [comment]
I forgot to mention that you could keep things as you have them, but use pojoQueryBuilder.term() rather than pojoQueryBuilder.range() on your topics match.  The semantics of a term (word or phrase) match are different than a value match, but hopefully similar enough to meet your needs.  The only problem would be if one topic is found inside another topic.

**Comment by malteseduck** [comment]
Thanks, I will try your ideas.
