### ISSUE TITLE
TransformExtensionsManager readAs method throws FailedRequestException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#384]
Using one of the Java IO classes to read a XSL transform code, causes a FailedRequestException.
The motive of this test was to validate Git Issue 332.

Since only users with the http://marklogic.com/xdmp/privileges/xdmp-eval-in (xdmp:eval-in) or equivalent privilege can send request parameter that enables the request to be evaluated against a content database other than the default  database associated with the REST API instance,the test creates a user called "eval-user" who has the following role "test-eval".

Role "test-eval" has the following previlages : 
```
"xdbc:eval", "xdbc:eval-in","xdmp:eval-in","any-uri","xdbc:invoke"
```
But 
```
TransformExtensionsManager readXSLTransformAs(transformName, FileReader.class)
```
throws an exception. Using a BufferedReader also threw same exception. Maybe the API usage in the test is missing something or incorrectly used.

Here is the sample test code:
```
	@Test	
	public void testXsltTransformReadAs() throws IOException, ParserConfigurationException, SAXException, XpathException, TransformerException
	{	
		System.out.println("Running testXsltTransformReadAs");

		String[] filenames = {"constraint1.xml", "constraint2.xml", "constraint3.xml", "constraint4.xml", "constraint5.xml"};
		String transformName = "search2html";

		DatabaseClient client = DatabaseClientFactory.newClient("localhost", Uberport, UberdbName, "eval-user", "x", Authentication.DIGEST);

		// set query option validation to true
		ServerConfigurationManager srvMgr = client.newServerConfigManager();
		srvMgr.readConfiguration();
		srvMgr.setQueryOptionValidation(true);
		srvMgr.writeConfiguration();

		// write docs
		for(String filename : filenames)
		{
			writeDocumentUsingInputStreamHandle(client, filename, "/response-transform/", "XML");
		}

		// set the transform		
		// create a manager for transform extensions
		TransformExtensionsManager transMgr = client.newServerConfigManager().newTransformExtensionsManager();

		// specify metadata about the transform extension
		ExtensionMetadata metadata = new ExtensionMetadata();
		metadata.setTitle("Search-Response-TO-HTML XSLT Transform");
		metadata.setDescription("This plugin transforms a Search Response document to HTML");
		metadata.setProvider("MarkLogic");
		metadata.setVersion("0.1");

		// get the transform file
		File transformFile = new File("src/test/java/com/marklogic/client/functionaltest/transforms/search2html.xsl");

		FileHandle transformHandle = new FileHandle(transformFile);

		// write the transform
		transMgr.writeXSLTransform(transformName, transformHandle, metadata);

		// get the combined query
		File file = new File("src/test/java/com/marklogic/client/functionaltest/combined/combinedQueryOption.xml");

		String combinedQuery = convertFileToString(file);

		// create a handle for the search criteria
		StringHandle rawHandle = new StringHandle(combinedQuery);

		QueryManager queryMgr = client.newQueryManager();

		// create a search definition based on the handle
		RawCombinedQueryDefinition querydef = queryMgr.newRawCombinedQueryDefinition(rawHandle);
		querydef.setResponseTransform(new ServerTransform("search2html"));

		// create result handle
		StringHandle resultsHandle = new StringHandle();
		queryMgr.search(querydef, resultsHandle);

		// get the result
		String resultDoc = resultsHandle.get();

		System.out.println(resultDoc);

		assertTrue("transform on title is not found", resultDoc.contains("<title>Custom Search Results</title>"));
		assertTrue("transform on header is not found", resultDoc.contains("MyURI"));
		assertTrue("transform on doc return is not found", resultDoc.contains("<td align=\"left\">/response-transform/constraint5.xml</td>"));

		
		FileReader srtReadXSLTCodeHandle1 = transMgr.readXSLTransformAs(transformName, FileReader.class);

		transMgr.deleteTransform("search2html");

		// release client
		client.release();		
	}

```

Here is the stack trace:
```
com.marklogic.client.FailedRequestException: Local message: config/transforms read failed: Bad Request. Server Message: REST-UNSUPPORTEDPARAM: (rest:UNSUPPORTEDPARAM) Endpoint does not support query parameter: database
	at com.marklogic.client.impl.JerseyServices.getValue(JerseyServices.java:2733)
	at com.marklogic.client.impl.TransformExtensionsImpl.readTransform(TransformExtensionsImpl.java:197)
	at com.marklogic.client.impl.TransformExtensionsImpl.readXSLTransform(TransformExtensionsImpl.java:182)
	at com.marklogic.client.impl.TransformExtensionsImpl.readXSLTransformAs(TransformExtensionsImpl.java:147)
	at com.marklogic.client.functionaltest.TestDatabaseClientConnection.testXsltTransformReadAs(TestDatabaseClientConnection.java:535)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:19
```

**Comment by kcoleman-marklogic** [comment]
It sounds like the Java API is passing the "database" param to `GET /v1/config/transforms/{name}`. That method has no such param. The database param applies only to operations on the content db; transforms live in the modules db.

It might be worth verifying /v1/config/resources/{name} doesn't have the same problem, if we haven't already done so. Or the other /v1/config/* methods, if you're out of things to do. ;)

**Comment by sammefford** [comment]
I have a  proposal for how to fix this.  Let's throw an IllegalStateException on calls to newTransformExtensionsManager() if the client has a database set, since the /v1/config/transforms REST endpoint doesn't allow the database parameter. Additionally, in case someone sets the database after calling newTransformExtensionsManager(), we can throw an IllegalStateException when any method is called on TransformExtensionsManager which would contact the server.  

Let's fix this in 4.0 since it might break someone who is already doing that (though that's unlikely).  For 3.0.5, let's not have any tests that attempt to set the database when using TransformExtensionsManager.  Make sense?

I'll keep this task for me to throw the IllegalStateException where appropriate.

**Comment by kcoleman-marklogic** [comment]
So I have to create a separate connection (DatabaseClient) just because I want to do a config operation?

Maybe I've lost track of the issue, but I don't understand why this needs to be an error at all. The db is just an override for the default content db associated with the REST instance. The db split is already and always present. It's not as if, when you specify no db, the CRUD/search operations and the config operations are operating on the same database. 

The API impl should just do The Right Thing: Use the override on content db operations, and not use it on modules db operations.

**Comment by sammefford** [comment]
You should most likely create a separate connection when doing a config operation because you should most likely be using a separate user with privileges to do a config operation.  Only in development land do we get to do everything as "admin".

I lean towards having the Java Client API to mirror the REST API: throw an error when someone specifies a database on a config operation.  The problem with not throwing an error is we're silently ignoring their request to operate on another database.  I can see scenarios where an instance of MarkLogic server has multiple REST endpoints, each with a separate modules database.  I don't want customers to think they could use one database client instance to configure both modules databases, because they can't--the REST endpoint doesn't even support the database parameter.  

This new world we're in is even slightly more confusing because many of our config operations, such as LibraryExtensionsManager are rendered redundant by the ability to read/write directly to the modules database by specifying it at the DatabaseClient.  Since we can do that, I don't want to give the mistaken impression that we could also use LibraryExtensionsManager or any of the other config managers against a separate modules database if we really can't.  Therefore I'm voting that we throw an error (just like the REST API) to make it clear that's not allowed.

**Comment by kcoleman-marklogic** [comment]
I don't understand the concern about being consistent with the REST behavior. The REST API is throwing an error because the API is using it wrong, not because there's something special about passing it the database parameter. If the Java API passed it a parameter named "sausage", you'd get the same behavior. The user isn't doing anything wrong. We are.

I think as long as we talk about the parameter in terms of the content database, there's no need to fear the database entanglement, either. The REST dev guide, REST apidoc, and the Java dev guide all talk about this knob as changing the CONTENT database. The javadoc doesn't, which may be where your concern arises. It just says the following, which is misleading:

"database - the database to access (default: configured database for the REST server)"

Anyway, I'll take pity on the poor horse and stop beating it now. :)

**Comment by sammefford** [comment]
A few more beatings . . .

I'm trying to say the user is doing something wrong if they use a DatabaseClient pointed to a non-default database and attempt to do a config operation with that DatabaseClient.  We made the choice to attach non-default database config to the DatabaseClient and we agree that we need to make sure it's clear that only applies to changing operations against he CONTENT database.  I agree we need to improve the javadocs to clarify that.  

As a principle, however, let's lean towards "fail fast" rather than silently accept misuse.  I submit that it's misuse to attempt config operations when the DatabaseClient is pointed at a non-default database.  Now I too will leave the horse to rest. ;)

**Comment by sammefford** [comment]
After some discussion with the team, we're going to mark this "will not fix" since the current behavior is doing what it should: throw an error for an ambiguous call.  The call is ambiguous because it is pointing to a different database which might mean the dev incorrectly thinks they can change modules in a different database than the default modules database for the REST server.  The solution is to perform any rest-admin calls using a DatabaseClient instance configured with no specific content database--that way it's clear that the dev expectes the calls to affect the default modules database for that REST API instance.
