### ISSUE TITLE
Remove limitation on <T> for RuleManager.matchAs methods

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#386]
Erik, do you think it's a mistake that RuleManager. matchAs methods restrict <T> to RuleListReadHandle?  I'm thinking like other *As shortcut methods, <T> should be open-ended.  Am I mistaken?

**Comment by grechaw** [comment]
I think the original restriction was deliberate, but that doesn't mean you're wrong.   The rationale was that it only exists for the java interface to rule lists.  But we've weakened that reasoning since the original implementation of Java API, and if you can see a reason for allowing open-ended access you may as well implement it.

**Comment by sammefford** [comment]
I don't see a reason for allowing open-ended access.  I haven't dug into what it does enough to make a recommendation.  I'm just asking the question because I don't see the difference between match methods and matchAs methods with this restriction in place . . .

**Comment by ehennum** [comment]
I think it is a bug -- either we shouldn't have the matchAs() method or it should be unrestricted.

**Comment by sammefford** [comment]
Thanks for the input, guys.  I'll fix it.

**Comment by sammefford** [comment]
Nevermind, false alarm here.  The methods were good.  But good thing I had task #366 because it caused me to add a javadoc @param tag which might clarify a bit that the <T> there refers to the handle to be populated, not the IO object passed as the first argument.  In that way it's different than other *As methods . . . it's a bit backwards.  But that's to be expected with reverse queries, right ;) ?
