### ISSUE TITLE
Support for processing each row as a separate JSON, XML, or POJO Structure

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#452]
Optic API for Java needs to provide support for processing response as each row of separate JSON, XML and Pojo structure in the RowManager class.

Here is the sample code from functional Spec write up for this:

``` java
// alternative 4: get each row as a separate JSON tree
for (JsonNode row: mgr.resultRowsAs(plan, JsonNode.class)) {
    ... // navigate the JSON tree for this row
}

// alternative 5: get each row as a separate XML tree
for (Document row: mgr.resultRowsAs(plan, Document.class)) {
    ... // navigate the XML tree for this row
}

// alternative 6: get each row as a POJO tree via JSON databinding
for (JacksonDatabindHandle<SomePojo> rowHandle: mgr.resultRows(plan, new JacksonDatabindHandle(SomePojo.class))) {
    SomePojo row = rowHandle.get();
    ... // use the POJO for this row
}

// alternative 7: get each row as a POJO tree via XML databinding
JAXBContext context = JAXBContext.newInstance(SomePojo.class));
for (JAXBHandle<SomePojo> rowHandle: mgr.resultRows(plan, new JAXBHandle<SomePojo>(context))) {
    SomePojo row = rowHandle.get();
    ... // use the POJO for this row
} 
```

**Comment by ehennum** [comment]
As we discussed, it is not clear that this design is possible because the generic of the RowSet is the class of the handle, not the content. It certainly isn't appropriate to try to add a hack in EA3.

Note that the limitation is only on the conveniences for the wrapped content classes, not on the handles. Java Optic API does have tested support for the handles:

https://github.com/marklogic/java-client-api/blob/develop/src/test/java/com/marklogic/client/test/RowManagerTest.java#L205

**Comment by ehennum** [comment]
An earlier change decoupled RowSet from read handles, which had the side effect of removing the design obstacle. 

You can see the unit tests in com.marklogic.client.test.RowManagerTest#testResultRows() within the xmlshortcut and jsonshortcut tags

It would be especially nice to confirm the that, after registering a JAXB class, you can iterate over the rows with implicit databinding to objects of that class.

**Comment by georgeajit** [comment]
Tested in TestOpticOnViews.
