### ISSUE TITLE
PojoQueryBuilderImpl wrapQueries

### ISSUE THREAD

**Issue by malteseduck** [marklogic/java-client-api#522]
In many of the methods for building queries for POJOs there is a check to see if `wrapQueries` is set to `true` before it prefixes path information, creates container queries, etc.  The`pojoPropertyPath()` method:

https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/impl/PojoQueryBuilderImpl.java#L53

does not do a similar check.  Would something like this:

```
    private StructuredQueryBuilder.PathIndex pojoPropertyPath(String pojoProperty) {
        if (wrapQueries) {
            return pathIndex(classWrapper + "/" + pojoProperty);
        } else {
            return pathIndex("/" + pojoProperty);
        }
    }
```

be more appropriate to honor that `wrapQueries` state, or are there things that would break or other reasons it should not be implemented this way?

**Comment by sammefford** [comment]
Perhaps there's something that needs to be done here, but I'll be surprised if that's it.  The wrapQueries check is only in effect after you've called containerQueryBuilder (because you want to do the equivalent of an cts:element-query in XQuery).

Any chance you could share the query you're doing and the scenario that's not working?  I can create one, but it would be easier if we're looking at the same thing.

**Comment by sammefford** [comment]
Let me clarify further that the expected path range indexes are the ones you'll see from using the annotation \@PathIndexProprty and [running GenerateIndexConfig](http://docs.marklogic.com/guide/java/binding#id_29989).  In all cases the path will be classWrapper/pojoProperty because that's how the data is in the doc (every POJO property is nested in a class wrapper).  So classWrapper is not optional like wrapQueries is.

Perhaps all you need to do is add the annotation, run GenerateIndexConfig and see what the expected path range index is?

**Comment by malteseduck** [comment]
It wasn't necessarily a matter of something "not working", exactly.  I think I see where I have not thought this through fully.  We "extended" the POJO repository so we could do some custom settings to the object mapper (one of which was to not have the class wrapper) for some interoperability issues we were having between some Node.js stuff and Java stuff.  In that we instantiate an extension of `PojoQueryBuilderImpl` (yeah, I know) that sets `wrapQueries` to false and has a `pojoPropertyPath` method like that above so it doesn't prefix the path.  We just put documents in a "Person" collection as opposed to a "com.bubba.Person" collection, and the JSON document is "simple" JSON without the wrappers.

If we were doing it "right" we wouldn't "see" the `PojoQueryBuilderImpl.class` at all and setting the `wrapQueries` to false wouldn't even be an option.  

Your suggesting on running GenerateIndexConfig is probably a good one so I can better understand how it all works.  I have never used the containerQueryBuilder before so I should look more into that.  The more I understand how everything "should" work the more "extensions" I can get rid of.  This sounds like more I need to learn instead of you updating something at the moment.  

Maybe I have more a question of "what are the downsides of not having the classWrapper prefix on everything, and if there are no major downsides is it worth allowing configuring a PojoRepository such that things are not wrapped?"  We have been doing it like that for the last couple years without issue but we don't have 100s of Java/MarkLogic apps so we are probably just lucky.  I can see how having a "com.bubba.Person" and "com.lubba.Person" might lead to some issues since they both are treated as "Person" with our "hacks".  

Thanks for your time, by the way, Sam.

**Comment by malteseduck** [comment]
Given these classes

`package lds.stack.examples.marklogic.model;

import com.marklogic.client.pojo.annotation.Id;
import com.marklogic.client.pojo.annotation.PathIndexProperty;

import java.util.List;
import java.util.UUID;

public class Event {
    @Id
    public String id;
    @PathIndexProperty(scalarType = PathIndexProperty.ScalarType.STRING)
    public String name;
    public List<Room> rooms;

    public Event() {
        this.id = UUID.randomUUID().toString();
    }

    public Event(String name, List<Room> rooms) {
        this();
        this.name = name;
        this.rooms = rooms;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Room> getRooms() {
        return rooms;
    }

    public void setRooms(List<Room> rooms) {
        this.rooms = rooms;
    }
}
`
package lds.stack.examples.marklogic.model;

public class Room {
    public String name;
    public Type type;

    public Room() {
    }

    public Room(String name, Type type) {
        this.name = name;
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }
}
`

`
package lds.stack.examples.marklogic.model;

import com.marklogic.client.pojo.annotation.PathIndexProperty;

public class Type {
    @PathIndexProperty(scalarType = PathIndexProperty.ScalarType.STRING)
    public String name;

    public Type() {
    }

    public Type(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
`

I get the following indexes generated:

`
 {
      "path-expression" : "lds.stack.examples.marklogic.model.Event/name",
      "scalar-type" : "string",
      "collation" : "http://marklogic.com/collation/",
      "range-value-positions" : "false",
      "invalid-values" : "ignore"
    },
    {
      "path-expression" : "lds.stack.examples.marklogic.model.Type/name",
      "scalar-type" : "string",
      "collation" : "http://marklogic.com/collation/",
      "range-value-positions" : "false",
      "invalid-values" : "ignore"
    }
`

I was trying to use `containerQueryBuilder()` to do a range query on the `Type.name`, is that possible?  It was getting choked up on the fact that rooms was a `java.util.List`.  Maybe I did it wrong?  Is it possible if my `rooms` was just a `room`:

`qb.containerQueryBuilder("room", Room.class).containerQueryBuilder("type", Type.class)` 

...or is the only way to use `qb.range(qb.pathIndex(....))`

**Comment by sammefford** [comment]
I don't see a way to do that.  

I tried this:

    PojoQueryBuilder<Event> qb = eventRepo.getQueryBuilder();
    PojoQueryBuilder<Room> roomQueryBuilder = qb.containerQueryBuilder("rooms", Room.class);
    PojoQueryBuilder<ArrayList> typeQueryBuilder = roomQueryBuilder.containerQueryBuilder("type", ArrayList.class);
    PojoQueryBuilder<Type> typeQueryBuilder = roomQueryBuilder.containerQueryBuilder("type", Type.class);

And I get the error:

```
Exception in thread "main" java.lang.IllegalArgumentException: property type not found, getType not found, and setType not found in class java.util.List
        at com.marklogic.client.impl.PojoQueryBuilderImpl.getType(PojoQueryBuilderImpl.java:319)
        at com.marklogic.client.impl.PojoQueryBuilderImpl.containerQueryBuilder(PojoQueryBuilderImpl.java:70)
        at LdsPojos.main(LdsPojos.java:25)
```

Because, of course, ArrayList doesn't have a getType method.  But it seems reasonable to me that we could support a Collection of Pojos.  Would it be helpful if we file an RFE for that?

Again, in the short-term, the work-around is to use JacksonDatabindHandle that should provide a more open-ended feature set.

**Comment by sammefford** [comment]
You could probably do a term query or a word query, however, using roomQueryBuilder.  Perhaps you could even get away with a value query instead of a range query.  Should I see if I could make that work?  Or is that not going to meet your needs?

**Comment by sammefford** [comment]
I don't know how much this helps, but here's how to do it using JacksonDatabindHandle:

    // do this before you create your DatabaseClient
    DatabaseClientFactory.getHandleRegistry().register( JacksonDatabindHandle.newFactory(LdsEvent.class) );
    ...

    ArrayList<Room> rooms = new ArrayList<>();
    rooms.add(new Room("room_a", new Type("type_a")));
    Event event = new Event("event_a", rooms);
    client.newDocumentManager().writeAs(event.id, event);

    StructuredQueryBuilder qb = new StructuredQueryBuilder();
    StructuredQueryDefinition query = qb.containerQuery(qb.jsonProperty("rooms"),
      qb.range(qb.pathIndex("type/name"), "xs:string", "http://marklogic.com/collation/", Operator.EQ, "type_a"));
    DocumentPage docs = client.newDocumentManager().search(query, 1);
    for ( DocumentRecord doc : docs ) {
      Event matchingEvent = doc.getContentAs(Event.class);
      System.out.println(matchingEvent);
    }

**Comment by malteseduck** [comment]
So the registration of the class allows the getContentAs to work? Am I understanding that correctly?

**Comment by malteseduck** [comment]
Most POJOs I have designed have some sort of collection in it, that is just how it has worked out.  As I have never used the containerQueryBuilder() function I haven't had an issue, but I can see how supporting more complicated JSON models would be useful.  Then again, if people aren't complaining it may not be worth it, and I am fine without it at the moment because most of the queries I do are value queries and I can do container queries and value queries and that mostly works fine. 

What would be most useful for us is a little more configurability on how the JSON is stored in the database.  For us, just the ability to "turn off" the class wrappers was all we really needed, but we kind of had to "hack" to get it to work.  Being able to get at the object mapper inside the PojoRepository and having that used throughout, plus the ability to turn off "wrapQueries" is what we need.  Maybe in general this exposing more configuration would expose a bunch of problems and that might be why it might not be an option.  That is the main question I wanted to ask, the "wrapQueries" one I started with was just a step towards this.

**Comment by sammefford** [comment]
Thanks, @malteseduck.  I'll create the RFE for supporting collections with containerQueryBuilder.  I think it's a good enhancement.

By "wrapQueries" what I think you mean is turn off JsonTypeInfo.As.WRAPPER_OBJECT.  In PojoQueryBuilderImpl "wrapQueries" actually refers to container queries, so it's not related to the persisted class wrappers.

For testing purposes, you can access the ObjectMapper using

    ((PojoRepositoryImpl) pojoRepository).getObjectMapper()

we didn't expose that because it starts you down a path that could easily break things.  For example: removing the persisted class wrappers might break things.  We need those if we're going to do any kind of simple containerQueries (containerQueryBuilder) or range queries on nested types.  You've been fine without it since you haven't done containerQueries or range queries on nested types.  

Your scenario is the perfect example where you have two nested classes with the property "name".  We use the class wraper to create path range indexes that are class-specific, so you can query Type/name or Room/name not just any "name" property at any level.  Of course, if you always nest only one way (no Room or Type objects inside any other objects), you could create full-path range indexes like /rooms/type/name, but we didn't see a way to fit that type of path range index into PojoQueryBuilder as it is now, so we stuck with container queries and versitile path indexes like Type/name.

In any case, when you ask the question of whether or not you can tweak the persisted structure, you're headed down a path that's better served by JacksonDatabindHandle in combination with JSONDocumentManager and StructuredQueryBuidler than by PojoRepository.  Does that make sense?

**Comment by sammefford** [comment]
Sorry, I missed one of your questions:

> So the registration of the class allows the writeAs/getContentAs to work? Am I understanding that correctly?

Yes, you understood that correctly, when it comes to POJOs.  There are many types pre-registered for you (byte[], Document, File, InputSource, InputStream, JsonNode, JsonParser, Reader, Source, String, XMLEventReader, XMLStreamReader), see [HandleFactoryRegistryImpl.registerDefaults](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/impl/HandleFactoryRegistryImpl.java#L45-L60).  But to register your own POJOs you'll need to pass the return value of JacksonDatabindHandle or JAXBHandle newFactory methods to DatabaseClientFactory.getHandleRegistry().register().

**Comment by malteseduck** [comment]
Your explanation makes sense, I can see where opening things up could break things or cause a lot of support issues with people breaking themselves.  We had used the `((PojoRepositoryImpl) pojoRepository).getObjectMapper()` to update the wrap, and had created some classes that we used to work around alot of the class wrappers and such in range queries, etc.  I was trying to take advantage of all the good things you had with PojoRepository and PojoQueryBuilder but we may have ended up with something more complicated than just using the JacksonDatabindHandle and such as you suggest.  I will look more into using that approach.  Thanks
