### ISSUE TITLE
Demonstrate pause/resume

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#561]
Illustrate how to resume after a fatal error, for example a bug in server-side transformation code or the Java application that invokes the DMSDK. Track and report progress that has been made and pickup where things were left off without losing/repeating any data. Applicable to ingest, transform, and export.

Migration of marklogic/data-movement#93.

**Comment by sammefford** [comment]
Here's a quick brain-dump of some possible failure scenarios for WriteBatcher:
1. A mal-formed document or uri is rejected
2. An error in MarkLogic server is rejecting all writes
3. A temporary network error causes some batches to fail
4. The client JVM is stopped unexpectedly or otherwise stops functioning
5. The process feeding documents to WriteBatcher fails
6. In addition to 2, 3, or 5 above, new documents have been added to the source, preventing a simple restart with skipping all docs below lastSuccessBatchNumber * batchSize
7. Document updates are coming in and should overwrite some files written previously, but the source cannot provide a version number or lastModified timestamp for each file.

Recovery options
1. Register an onBatchFailureListener to retry writing the documents from the failed batch one at a time. Log which documents fail and what the error is for each. Then manually review the log and correct each mal-formed document or uri.
2. Register an onBatchSuccessListener to track in a log file the highest number of successful batch (e.g. lastSuccessBatchNumber). When restarting the job, read lastSuccessBatchNumber from the log file and skip all documents below that highest batch number--that is, iterate over documents in the same order each time and don't send documents to WriteBatcher.add or addAs if they are below lastSuccessBatchNumber * batchSize. Optionally, stop the job after a certain number of subsequent batch failures or listener failures.
3. HostAvailabilityListener will most likely detect this scenario and retry the batch against another host on your cluster or stop the job if none are available. If HostAvailabilityListener is not handling this scenario, either add your exception to HostAvailabilityListener.withHostUnavailableExceptions or create a new listener that handles the scenario better, perhaps calling batcher.retry or batcher.retryWithFailureListeners as appropriate.
4. Handle the same as (2)
5. Handle the same as (2)
6. Register an onBatchSuccessListener to track in a log file the uris (or other unique id) of each successful document. When restarting the job, read the successful uris from the log file and skip those documents --that is, iterate over source documents and don't send documents to WriteBatcher.add or addAs if they are in the list of successful documents.
7. Register an onBatchSuccessListener to track in a log file the uris and a computed checksum over the contents of each successful document. When restarting the job, read the successful uris and checksums from the log file and skip those documents where the checksum matches for the source document and the successfully written document.

Here's a quick brain-dump of some possible failure scenarios for QueryBatcher:

10. A document in the batch provided to the listener has been deleted before the listener can read the document
11. An error in MarkLogic server is throwing an error on all queries
12. A temporary network error causes some batches to fail
13. The client JVM is stopped unexpectedly or otherwise stops functioning

Recovery options:

10. Configure your QueryBatcher by calling withConsistentSnapshot.  Then if you're using ExportListener or ExportToWriterListener configure those by calling withConsistentSnapshot.  If you have a custom listener, get the snapshot timestamp from QueryEvent.getServerTimestamp().  Use that timestamp to read the batch of documents with DocumentManager.read(long serverTimestamp, String... uris) or similar.  That will get you the documents as they were when the job started.
11. Register an onQuerySuccessListener to track in a log file the uris (or other unique id) of each successful document.  When restarting the job, read the successful uris from the log file and skip those documents --that is, iterate over batches of uris matching the query and don't have the custom listener do anything with documents that are in the list of successful documents. 
12. Same solution as (3) above
13. Handle the same as (11)
