### ISSUE TITLE
wb.awaitCompletion() and wb.awaitTermination() getting called after stopping wb instance

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#584]
Currently, wb.awaitCompletion() and wb.awaitTermination() are not throwing any exception when they are called after the 'wb' instance has been stopped.

**Comment by sammefford** [comment]
I don't see any risk in calling those methods after stopping wb instance.  They should just return immediately.  I think current behavior is acceptable.  By the way, I just logged #586 - remove awaitTermination since I don't see any significant difference between awaitCompletion and awaitTermination
