### ISSUE TITLE
batch.getClient().getDatabase() returns null in the callbacks

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#589]
batch.getClient().getDatabase() in the snippet below returns null
```
WriteBatcher ihb1 =  dmManager.newWriteBatcher();
		ihb1.withBatchSize(1);
		ihb1.onBatchSuccess(
		        batch -> {
		        		System.out.println(batch.getClient().getDatabase());    
		         	
		          }
		        )
		        .onBatchFailure(
		          (batch, throwable) -> {
		        	System.out.println(batch.getClient().getDatabase());    
		          });
		dmManager.startJob(ihb1);
	
		for (int i =0 ; i < 10; i++){
			String uri ="/local/json-"+ i;
			ihb1.add(uri, stringHandle);
		}
```

**Comment by sammefford** [comment]
I'm guessing this is expected behavior.  But it's a bit convoluted to explain.

The short explanation is we don't promise to populate the database name.  

The longer explanation is when you create your DatabaseClient if you don't tell us your database, we don't know what it is, so it will use the default database for your REST port, and getDatabase will return null.  However, in the case of DMSDK, we create some DatabaseClient instances for you after asking the server for a list of forests, their hosts, and their database.  At that point we know the database and I believe we populate it in the DatabaseClient instances we creeate.  So the DatabaseClient instances we create might return something from getDatabase, but we still use the original DatabaseClient  you created, and that might not have the database populated.  And that's as expected.
