### ISSUE TITLE
Batched SPARQL CONSTRUCT queries

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#600]
Break CONSTRUCT queries up into batches for large-scale, multi-transaction triple inserts.

**Comment by grechaw** [comment]
? CONSTRUCT is for query, not insert.  Please clarify

**Comment by jmakeig** [comment]
@grechaw, maybe I don’t understand how one would use `CONSTRUCT`. Isn’t the point to generate triples to add them to the database? Generating triples for a one-time export would also be another good use case for batching with the Data Movement SDK.

**Comment by sammefford** [comment]
@grechaw any thoughts on this?

**Comment by grechaw** [comment]
@jmakeig your concept is valid, you're just naming the wrong part of the query language.

SELECT, CONSTRUCT, ASK, and DESCRIBE are the four keywords for querying the database.  They are reads and part of SPARQL 1.0

INSERT WHERE is part of SPARQL update and does what you're looking for.  SPARQL UPDATE statements can already be batched together, as part of the language.  you just separate update statements with a semicolon.

**Comment by grechaw** [comment]
There are two limitations on using multiple statements with SPARQL UPDATE.  We've discussed the shortcomings of the design but have no way to change it at this time.

1.  if you put multiple SPARQL UPDATE statements into a single query, they are all executed as one transaction.  The payload defines a transaction boundary.
2.  if you include just one UPDATE statement per query, then the statements can be put into a multi-statement transaction.

What is missing is the ability to batch a bunch of statements AND say 'these are part of a bigger transaction'.  We don't do this because in adhering to the SPARQL UPDATE spec, option #1 must be committed as part of the request cycle.  So this issue could be requesting functionality that closes this gap
