### ISSUE TITLE
Custom JobReportListener

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/java-client-api#615]
I’m trying to do something fun today. Recall my previous example. This is the core of the data hub framework. The corblike thing:
 
1. Get array of uris from marklogic via rest extension
1. Use querybatcher to iterate over them
1. Call my custom rest extension to process each batch
 
Inside my custom rest extension I’m doing something like this:

```xquery
for $uri in $uris
return
  try {
    doSomething($uri)
  } catch($ex) {
    ()
  }
``` 

the point being that for a batch of 10 items, it’s ok for 1 item to fail.
 
What I’d like is a JobReport that tells me the correct # of individual uris that failed.
 
So let’s say I have 100 items and only 1 fails.
 
I’d like to see my jobreport with:
```json 
"successEventsCount": 99,
"failureEventsCount": 1,
"successBatchesCount": 10,
"failureBatchesCount": 0
 ```

For my purposes all 10 batches succeeded. But I have 1 failureEventCount.
 
I noticed that the QueryJobReportListener is only updating the batchFailure in processFailure. And that the default JobReportImpl is using batchFailure for failureEventsCount.
 
What’s the best path for me to get the kind of report I want?

Is it to register my own JobReportListener?

Or perhaps it’s to file a ticket to get the default altered?

**Comment by sammefford** [comment]
Yes, registering your own custom listener is the best path.  By design, the built-in listeners cannot meet the needs of every custom job.  The core of DMSDK is to enable data movement applications, therefore the OOTB listeners and JobReport serve mostly as working examples of the kinds of things custom applications will want to do.  The work of custom applications happens in the listeners.  In your case, I'd recommend you instantiate four instances of AtomicLong outside your batcher, one per metric you're tracking. They are a thread-safe way to increment your counts across all the threads that run your listener.  For an example of this, here's an excerpt from [ApplyTransformTest](https://github.com/marklogic/java-client-api/blob/develop/src/test/java/com/marklogic/client/test/datamovement/ApplyTransformTest.java#L137-L168)

    StructuredQueryDefinition query3 = sqb.value(sqb.jsonProperty("testProperty"), "test3a");
    final AtomicInteger count3 = new AtomicInteger(0);
    QueryBatcher batcher3 = moveMgr.newQueryBatcher(query3)
      .withBatchSize(100)
      .onUrisReady(batch -> count3.addAndGet(batch.getItems().length))
