### ISSUE TITLE
JavaDoc code snippets are unreadable in Eclipse

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#619]
I'm still seeing marklogic/data-movement#130 in EA4. It makes the examples mostly unusable in Eclipse.

**Comment by kcoleman-marklogic** [comment]
Can you clarify what "in EA4" means and/or provide a specific class where you're running into this? 

I only ask because the particular code sample sited in 130 looks fine on pubs, and usually when the javadoc markup is f'd up, it's f'd up everywhere. Which is to say, we don't perform any transforms on it to display it on pubs.

**Comment by kcoleman-marklogic** [comment]
Changing the severity level because I think it is REALLY hard to justify this as a "critical" bug. Let's be real, here.

**Comment by kcoleman-marklogic** [comment]
The code sample cited in 130 looks fine EVERYWHERE except the Eclipse tooltip. It even looks fine if you ask Eclipse to pull it up in its embedded browser. I really think this is an Eclipse problem. I believe the markup, both in javadoc and as rendered in the generated HTML, is fine and correct. 

This is beyond me at this point, so I'm giving it to Sam to puzzle over the vagaries of the Eclipse implementation. I think we should fix this if we can, but I also think it is a minor bug, given there is a workaround: You can pull up the perfectly well formatted javadoc from right inside Eclipse, without chipping a nail.

**Comment by sammefford** [comment]
I just discussed with Justin, and this is a corner case for people who have their application in eclipse depend on a java-client-api develop project also in eclipse.    The common case is those who have maven or gradle projects which depend on binaries from maven central.  Since we'll also have our javadocs in maven central, they can right-click on their project in eclipse, then choose Maven->Download JavaDoc.  It then takes some time to download, and they might have to choose Project->Clean or F5 (refresh) since I tried both, but eventually Eclipse shows them only the fully-beautiful javadocs not the half-baked ones.  Another option for our customers is to [use this](http://maven.apache.org/components/maven-eclipse-plugin/examples/attach-library-sources.html) in their pom.xml.  Also, they can click Window->Preferences->Maven->Download Artifact Javadoc to permanently download javadocs for all their projects.  I just learned all this today, so presumably it's not too hard for our customers to find.

**Comment by sammefford** [comment]
Ajit, can you verify that if you create a new project in eclipse and follow the instructions I just shared, that you can see the javadocs for QueryBatcher with correct formatting?  Here's the pom.xml for the new 
project I just created today.

```xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.marklogic</groupId>
	<artifactId>testEA4</artifactId>
	<packaging>jar</packaging>
	<version>0.1</version>
	<repositories>
		<repository>
			<id>MarkLogic-releases</id>
			<name>MarkLogic Releases</name>
			<url>https://developer.marklogic.com/maven2</url>
		</repository>
	</repositories>
	<dependencies>
		<dependency>
			<groupId>com.marklogic</groupId>
			<artifactId>marklogic-client-api</artifactId>
			<version>4.0.0-EA4</version>
		</dependency>
	</dependencies>
</project>
```

**Comment by jmakeig** [comment]
> do this in your POM file

Just to be clear, [the instructions](http://maven.apache.org/components/maven-eclipse-plugin/examples/attach-library-sources.html) aren’t modifications to the POM file, but the output of the`eclipse:eclipse` Maven goal, which is an Eclipse project configuration XML.

**Comment by sammefford** [comment]
Are you sure?  It says "or in your pom.xml...".  I thought that meant it was showing you how to add to your pom.xml an instruction for maven to download the javadocs.

**Comment by jmakeig** [comment]
I [got it working](http://stackoverflow.com/a/33653146/563324) in Eclipse. Our only requirement is to publish the source and JavaDoc JARs in the [correct place in the Maven repo](https://developer.marklogic.com/maven2/com/marklogic/marklogic-client-api/4.0.0-EA4/), which @georgeajit and @kkanthet have done for 4.0.0-EA4. The rest is the responsibility of the *client application* to configure the IDE environment.

In the user’s `build.gradle` in her application, she’ll need to configure her `eclipse` (and/or `idea`) task as such:

```groovy
plugins {
  id "java"
  id "eclipse"
  id "idea"
}

eclipse {
  classpath {
    downloadJavadoc = true
    downloadSources = true
  }
}

idea {
  classpath {
    downloadJavadoc = true
    downloadSources = true
  }
}
```

**Comment by jmakeig** [comment]
Pinging @rjrudin to socialize standardizing this practice.

**Comment by georgeajit** [comment]
Marked as shipped after discussing with Justin on 01/23/2017.
