### ISSUE TITLE
Remove deprecated APIs

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#621]
Many APIs were deprecated in ML8 and therefore are ready to be removed in ML9

**Comment by kcoleman-marklogic** [comment]
Sam, I have to put all this stuff into the release notes. I've tried to sift them all out of the diffs,  but I'm going to have dump a review task on you because I probably missed something.

**Comment by sammefford** [comment]
ok, thanks Kim!

**Comment by georgeajit** [comment]
Kim,

I have assigned this issue to you for documentation tasks, and status has been changed to fix, for now. Please change the Git labels and assignment, if this is not correct.

**Comment by kcoleman-marklogic** [comment]
That's fine, Ajit, thank you. I'll reassign it to Sam for review once the release notes are ready, unless you would like to do the review instead.

**Comment by kcoleman-marklogic** [comment]
The release note for the removed things is here:

http://pubs.marklogic.com:8011/9.0/guide/relnotes/chap4#id_23217

It includes both the items covered by this bug and the key-value interfaces that were probably removed previously. @sammefford please review between now and release, or pawn it off on Ajit. :)

**Comment by sammefford** [comment]
ServerConfigurationManager.setContentVersion

**Comment by kcoleman-marklogic** [comment]
Sam, you said ServerConfigurationManager.setContentVersion is missing from the release note, but I can't find any such method in either the ML8 or ML7 javadoc. There are deprecated get/setContentVersionRequests methods, and those are reflected in the release notes. 

I'm going to assume this is a misunderstanding unless I hear otherwise from you. I've incorporated the rest of your corrections, so unless I need straightening out on the content versioning thing, you can close this.

**Comment by sammefford** [comment]
Looks like I was mistaken in saying ServerConfigurationManager.setContentVersion.  I can see that ServerConfigurationManager.get/setContentVersionRequests are in the release notes as two of the removed methods, so I agree you captured that.
