### ISSUE TITLE
Remove WriteEvent.getBytesMoved since it's not implemented

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#631]

**Comment by jmakeig** [comment]
@sammefford, can you please create a new issue so that we can track this for a future release? After 4.0.1, we should sit down and review where we are with job instrumentation, reporting, and error handling and come up with some next steps. I think we’ve got the right architecture/abstractions in place, but there’s always more we can do to help developers figure out what’s going on (especially when things are unexpectedly slow or broken.)

**Comment by georgeajit** [comment]
WriteEvent does not have the method.
