### ISSUE TITLE
Make QBE queries paramaterizable

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#723]
As a Java developer, I don’t want to build JSON or XML QBEs as strings. String assembly in Java is difficult to write, difficult to read, and thus error prone. Ad hoc queries are handy in development and for quick examples, but as soon as you get to a real application, you want to lock down the particular queries and only provide parameters at runtime, sanitized for injection attacks. QBE should support this.

**Comment by ehennum** [comment]
This feature might be best implemented in the REST API:

*  A configuration service along the lines of /v1/config/query converts the parameterized QBE
   to a parameterized JSON or XML serialization of a cts:query and persists it on the server.

*  A query along the lines of /v1/semantics/sparql passes value bindings
   for the parameter placeholders.

Benefits:

*  Clients of all stripes get consistent templating of QBE.
*  We can get some performance benefits by skipping the QBE conversion to cts:query.
*  REST adminstrators can encourage applications with predictable performance by persisting queries. 

Bonus points:

*  Also save a search:query as a parameterized cts:query
*  Persist queries as modules instead of documents so the query is in the module cache

**Comment by ehennum** [comment]
One footnote:  the principle of persisting parameterized queries and supplying the value bindings in requests would apply not only to cts:query but also to SPARQL, SQL, and Optic queries.

**Comment by jmakeig** [comment]
Unless we're registering them like registered query, what's the advantage of persisting?
