### ISSUE TITLE
Instantiate DatabaseClient is taking too long

### ISSUE THREAD

**Issue by ltnd** [marklogic/java-client-api#734]
The client needs to create a stateless service on the JAVA Layer with final user authentication.
We can't keep the DatabaseClient in memory for this use case.
Instantiate the object each time a service is called is very long (500ms on the dev server used, around 400ms on my macBook pro 2015).

The test done : 
```
long time = GregorianCalendar.getInstance().getTime().getTime();
DatabaseClient dbClient = DatabaseClientFactory.newClient("127.0.0.1", 8000, "admin", "admin", Authentication.DIGEST);
System.out.println("Time to init dbClient : " + (GregorianCalendar.getInstance().getTime().getTime()-time));
```
The result : "Time to init dbClient : 398"

I know "setting up and tearing down the connection pool creates overhead", but it's a too big overhead for this use case.

**Comment by sammefford** [comment]
Thanks for the bug report!

What version of MarkLogic?  What version of Java?  What OS & version?

Are you doing anything else in this JVM?  For example, is this in a loop or is your measurement from a single JVM run of just these three lines?

**Comment by sammefford** [comment]
We recently found [a related issue](https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html) which affects DIGEST auth.  It is a delay due to a blocking call made by built-in security code to /dev/random when there wasn't enough entropy.  It doesn't make sense to me that you'd be facing the same issue since you're not making the network request so I don't see why DIGEST code should be run.  But just in case, here's the issue:

> A connection to MarkLogic server using JAVA client API with "digest" authentication can sometimes take a long time to establish.
> 
> DatabaseClientFactory.newClient("engrlab-129-192.engrlab.marklogic.com", 8000, new DigestAuthContext("admin", "admin")).newDocumentManager().exists("test.xml");

And here's the fix:

> In order to generate a pseudorandom number for client nonce in digest authentication, Java 8 by default uses /dev/random and it is a blocking call. If the entropy pool exhausts, it will block until sufficient entropy is available to return a pseudorandom number. Java 8 can be made to use /dev/urandom instead which is non-blocking. However, it can result in a lower quality random numbers if the entropy pool runs out. 
> 
> 1. Open the $JAVA_HOME/jre/lib/security/java.security file in an editor.
> 2. Change the line
> securerandom.source=file:/dev/random
> to 
>  securerandom.source=file:/dev/urandom
> 3. Save changes and exit the editor
> 
> An alternative work-around is to install an entropy generator such as haveged 
> https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged

**Comment by ltnd** [comment]
Sorry for the issue created with half the information.

What version of Java Client API?  => 3.0.6
What version of MarkLogic? => 8.0-6.4
What version of Java? What OS & version? => java version "1.8.0_45", on OSX Yosemite 10.10.5
Are you doing anything else in this JVM? For example, is this in a loop or is your measurement from a single JVM run of just these three lines? => single test of these 3 lines.

**Comment by ltnd** [comment]
We tried with "Authentication.BASIC" and it was the same performance

**Comment by sammefford** [comment]
It looks to me like the JVM is adding to the time here.  When I try it as you said, with just those three lines, it took as much as 1.8s for me.  I'm trying it on my windows laptop.  And as much as 45% of that time was not in the method call, so I'm guessing it's in the classloader since that's the first time DatabaseClient and DatabaseClientFactory are referenced.  When I changed it to four lines, the time in the call drops as low as 294ms for me, with 293ms of that in the call, so now it's just measuring the call:

    DatabaseClient dbClient = DatabaseClientFactory.newClient("127.0.0.1", 8000, "admin", "admin", Authentication.DIGEST);
    long time = System.currentTimeMillis();
    dbClient = DatabaseClientFactory.newClient("127.0.0.1", 8000, "admin", "admin", Authentication.DIGEST);
    System.out.println("Time to init dbClient : " + (System.currentTimeMillis()-time));

I'm curious how fast the second call to newClient runs for you when you try this.

**Comment by sammefford** [comment]
With all that said, the bulk of the time (284ms) is in the call to com.sun.jersey.client.apache4.ApacheHttpClient4.create.  For now that's not something I can optimize.  However, the current plan is to replace Jersey in 4.0.3: #65

**Comment by ltnd** [comment]
You are right ! 
I tried :
```
DatabaseClient dbClient = null;
try{
    dbClient = DatabaseClientFactory.newClient("127.0.0.1", 8000);
    dbClient.release();
    long time = GregorianCalendar.getInstance().getTime().getTime();
    dbClient = DatabaseClientFactory.newClient("127.0.0.1", 8000, "admin", "admin", Authentication.DIGEST);
    System.out.println("Time to init dbClient : " + (GregorianCalendar.getInstance().getTime().getTime()-time));
} finally {
    dbClient.release();
}
```
I had 60ms !
