### ISSUE TITLE
Support MarkLogic application-level auth

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic/java-client-api#766]
The Java Client API currently does not support application-level authentication.  This is an extremely important method of authentication to a broad base of MarkLogic customers.  Now that MarkLogic is endorsing 3-tier architectures for MarkLogic, application-level authentication becomes even more important because almost always the middle tier is authenticating some human actor on the front end then taking database actions on their behalf.  One of the only ways to authenticate such a user to MarkLogic is via application-level authentication.

In many customers this has been implemented in 2-tier architectures by passing user credentials (usernames, roles, cookies, etc) from an enterprise SSO or other system via HTTP headers.  This is by no means the only way this might be accomplished.  The key is to have an API- and product-supported means of transmitting this information such that the Java Client API can easily set credentials per request and the server can retrieve them for use in (usually) a custom authentication module.  

A generic HTTP header capability may be part of this effort, or maybe it would be better to create an implementation of `DatabaseClientFactory.SecurityContext` for application-level auth.

**Comment by sammefford** [comment]
Let me add quickly that "application-level auth" is a concept in MarkLogic named before the Java Client API existed.  It's confusing to talk about in the context of the Java Client API because it is for 3-tier architectures.  In 3-tier architectures the main "application" is in the middle tier.  It may be that the name "application-level auth" can still apply perfectly to whatever solution we come up with.  But for the moment I find it confusing because it seems that the classic MarkLogic way to do "applicaiton-levelo login" via the XQuery function xdmp:login was designed to be called by an XQuery application residing in MarkLogic server.

**Comment by sammefford** [comment]
Let's note that xdmp:login supports only role-based "static" authorization.  Some requirements demand "dynamic" authorization or rules that cannot be represented as roles.  This includes rules like "can only read this file during business hours".

**Comment by sammefford** [comment]
Let's note that if we're not using SAML but instead allowing the application to assert the roles, that could undermine the security of the database unless the database is requiring a reasonably secure authentication mechanism for the application, such as client-SSL-cert or Kerberos.

**Comment by tdiepenbrock** [comment]
Also let’s keep in mind that we never deploy marklogic into a secure environment without evaluating the security of the entire architecture.  The idea is that the overall architecture is secure, so that we can guarantee in the architecture that only trusted applications can connect to marklogic.  MarkLogic is rarely asked to provide the entire security solution.  However, that shouldn’t detract from the idea that Sam presented.  Sometimes we have to beef up the entire architecture to ensure that the application connecting to MarkLogic can be trusted, and if we could provide an additional authentication layer like what Sam presented we would be in a much better position.



Tom



Thomas Diepenbrock
Technical Manager
MarkLogic Corporation
Thomas.Diepenbrock@marklogic.com<mailto:Thomas.Diepenbrock@marklogic.com>
Cell:  +1 703 980 1248

[cid:0B48B25A-8630-42FD-BFB9-3092CB213523] <http://www.marklogic.com/social/>
<http://www.marklogic.com/social/>

On Jul 21, 2017, at 8:02 PM, Sam Mefford <notifications@github.com<mailto:notifications@github.com>> wrote:


Let's note that if we're not using SAML but instead allowing the application to assert the roles, that could undermine the security of the database unless the database is requiring a reasonably secure authentication mechanism for the application, such as client-SSL-cert or Kerberos.

**Comment by sammefford** [comment]
@tdiepenbrock how can you guarantee that only trusted applications can connect to MarkLogic?  The only ways I can think of are client-SSL-cert or Kerberos.  Most other solutions could easily be spoofed from the command-line or a nefarious app running on the same machine which normally runs the MarkLogic Java Client.  In other words, if a firewall only allows connections from the host where the MarkLogic Java Client runs, is that sufficient security?  My understanding is that's not.  In fact, with the number of major database hacks in the past few years, it seems the only way to be truly secure is to keep the data encrypted on the disk and use full database security so that even a hacker who has physical access to MarkLogic server cannot retrieve the data.  That approach is compromised if something outside the database can assert roles for a session without additional trust guarantees like requiring first app auth with client-SSL-cert or Kerberos.

**Comment by ehennum** [comment]
Client issue can be reopened if DHS embraces application-level authentication.
