### ISSUE TITLE
Document supported Java runtime

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#768]
MarkLogic only supports Oracle’s (née Sun’s) JRE. We should be specific in the documentation about platform, architecture, and runtime version.

[Here’s how mlcp does it](https://docs.marklogic.com/guide/mlcp/install#id_15275), for example.

**Comment by sammefford** [comment]
Kiran, can you take a crack at this?  I think you have better knowledge of which platforms and java version combinations we test.  In the mean-time I'll reach out to support to see what they think we should say that we officially support.

**Comment by kkanthet** [comment]
All our regression and local machines have Oracle Jvm’s, some of linux local vm’s have Open JDK but majority of our testing in on oracle java.
RH7 : 
builder@rh7v-intel64-90-test-35$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

Windows:
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

Mac:
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by sammefford** [comment]
Kiran, could you please comment about our envs for testing 3.x?  I believe those are running Java 1.7.

**Comment by georgeajit** [comment]
For Windows (winnt-64-w2k8-cluster) we are testing on Java 1.8 (jdk1.8.0_72)
For Linux (linux-64-rh6-cluster) we are testing on Java 1.7 (jdk1.7.0_79)

**Comment by sammefford** [comment]
Kim, here's my attempt at creating something like what mlcp has.

**Supported Platforms**
Java Client API is supported on the same platforms as MarkLogic Server, including 64-bit Linux, 64-bit Windows, and Macintosh OS X. For details, see Supported Platforms in the Installation Guide.

**Required Software**
All versions of the Java Client API require MarkLogic Server with a REST App Server configured. MarkLogic 8 and later versions come with a REST App Server pre-configured on port 8000.

The following software is required to use Java Client API 3.x:

- MarkLogic Server 8.x
- Oracle/Sun Java JRE 1.7 or later

The following software is required to use Java Client API 4.x:

- MarkLogic Server 9.x 
- Oracle/Sun Java JRE 1.8 or later


**Required Software for Rolling Upgrade**
Starting with Java Client API 4.0.1 each version of the Java Client API is supported with the latest version of the previous major release of MarkLogic Server.  This is to support rolling upgrade where the Java Client API is upgraded before MarkLogic Server.  This means Java Client API 4.x is supported against the latest version of MarkLogic Server 8.x to enable upgrading from Java Client API 3.x to 4.x prior to upgrading from MarkLogic Server 8.x to 9.x.  Note, however, that you should first upgrade your JRE to 1.8 in this scenario since Java Client API 4.x only supports JRE 1.8 or later.

**Comment by kcoleman-marklogic** [comment]
Saving only feedback from Sam or Justin, this done for 4.0.3 (and 3.0.9). If I get corrections today or tomorrow, I'll incorporate, but otherwise, this is going out as-is.
