### ISSUE TITLE
client-side load balance multiple MarkLogic hosts 

### ISSUE THREAD

**Issue by xmlking** [marklogic/java-client-api#781]
is there any way I can pass multiple hosts when I create new client, to client-side load balance between multiple MarkLogic hosts?   

```
newClient(host, port, username, password, authentication)
```

**Comment by sammefford** [comment]
Not for general operations.  If it did, there would of course be some things to consider: it would reduce the benefits of server-side caching, you'd need to keep any transactions on a single host, and you'd need to only talk to e-nodes (hosts with the REST server configured).  Nevertheless, MarkLogic Server is **very** efficient at server-side load-balancing even when all requests go to one host.  And the benefits of caching can be maximized that way.  

With that said, it can make sense to push that load-balancing out further for data movement (ETL) scenarios.  That's why we developed the [data movement SDK](http://docs.marklogic.com/guide/java/data-movement) which does the client-side load distribution for you.  It not only distributes writes across the cluster, but for queries it pulls each batch from a single forest then targets follow-up calls (such as export, transform, or delete) to the host responsible for that forest.

**Comment by xmlking** [comment]
Thanks @sammefford  for the information on `Data Movement API`. I will explore it. 
My usecase is to ingest  ~200M  300k size json files into 3 mid size marklogic nodes. 
With `java-client-api` and `Apache Spark` (which should be running on multiple client nodes)  I am getting 1500 TPS.   I am using WriteSet for 50. looking for advice on improving MarkLogic write performance.

**Comment by sammefford** [comment]
Those are some very large files!  What do you mean by TPS?  If that's docs/sec, then that seems like a good number given the size of your files.  Are you able to share your code?

It's hard to give tuning advice, knowing so little about your setup.  The WriteSet size of 50 might be ideal, but it just takes trial and error on different batch sizes to know what's best for your content.  When testing docs of size 10K we saw batch size of 500 was faster than batch size of 100.

Also, have you looked at [mlcp](http://docs.marklogic.com/guide/mlcp)?  It's a command-line tool.  For MarkLogic 8 that's the best way to load lots of files if your use case supports it.

**Comment by sammefford** [comment]
@xmlking are you still looking for help with this?  If not, I'll close.

**Comment by xmlking** [comment]
No. Thanks.
