### ISSUE TITLE
Set fields of NoResponseListener same as HostAvailabilityListener

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#828]
Currently, in order to  modify the suspend time or min hosts, we have to individually set them in both HostUnavailableListener and NoResponseListener . 
```
HostAvailabilityListener.getInstance(batcher).withSuspendTimeForHostUnavailable(Duration.ofSeconds(2)).withMinHosts(3);
NoResponseListener.getInstance(batcher).withSuspendTimeForHostUnavailable(Duration.ofSeconds(2)).withMinHosts(3);
```
Given the fact that NoResponseListener's processFailure is called only when the server goes down, can we by default set HostAvailabilityListener's suspend time , min hosts and other fields for NoResponseListener as well  and not expose the getInstance method for NoResponseListener  ?

**Comment by vivekmuniyandi** [comment]
As of now, we don't have any restriction on the presence of HostAvailabiityListener in the list of failure listeners. We are registering it by default to the instances but that doesn't prevent the customer to delete it by using the setQueryFailureListeners (in case of QueryBatcher) or setBatchFailureListeners (in case of WriteBatcher) and having no HostAvailabiityListener in the array they pass to the method. So there can be scenarios where there are no HostAvailabiityListener or they can have multiple HostAvailabiityListeners registered doing different stuffs when the host goes down. getInstance method returns the first HostAvailabiityListener registered with the batcher. Hence it would be difficult to generalize and use the same for both the listeners.

Also, I would like to think HostAvailabiityListener and NoResponseListener as two different listeners even though they handle the server being down and they are indeed two different objects. Also since we are configuring the settings by chaining, it would be impossible to set it to the NoResponseListener unless we change a whole lot of things.

**Comment by sammefford** [comment]
Also, remember that we don't expect customers to be commonly changing withSuspendTimeForHostUnavailable nor withMinHosts.  That seems like a very rare need for customers even though we do it frequently in our tests.
