### ISSUE TITLE
Remove Markdown from Javadocs

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#845]
We need to remove pegdown-doclet dependency since it's GPL.  Therefore we need to fix all javadocs that were written in Markdown and make them HTML instead, so they'll still look nice for end-users.

**Comment by jmakeig** [comment]
Huh? We haven’t changed the GPL code and we’re not redistributing it. What’s the issue?

**Comment by sammefford** [comment]
Looking closely at GPLv3.0 it says "convey" means "any kind of propagation that enables other parties to make or receive copies".  Therefore when we include markdown-doclet in our pom.xml that enables other parties to receive copies which means the pom.xml is effectively conveying GPL code, thus making this project liable to GPL restrictions.

**Comment by hansenmc** [comment]
The [pegdown](https://github.com/sirthias/pegdown) project says that it is deprecated and unmaintained anyhow. They suggest that people move to [flexmark-java](https://github.com/vsch/flexmark-java). It has a [BSD license](https://github.com/vsch/flexmark-java#license).

It might be worth looking to see if you could just swap out, rather than re-write the javadocs. Plus, it appears to be faster and supports more variants than pegdown.

**Comment by hansenmc** [comment]
You might still need a doclet. There is [MDoclet](https://github.com/mnlipp/jdrupes-mdoclet), but it's GPL 3.0 as well...

**Comment by sammefford** [comment]
I wasn't directly using pegdown, however, but pegdown-doclet which bundles pegdown into a javadoc doclet.  From [this post](https://www.richardnichols.net/2009/06/markdown-doclet-for-javadoc/) that apparently wasn't easy for them to create.

**Comment by sammefford** [comment]
@hansenmc , I looked an didn't find MDoclet.  While I was excited to see it, it's GPL also :(

**Comment by sammefford** [comment]
@vivekmuniyandi could you pull develop, build the javadocs (mvn javadoc:javadoc) and browse the datamovement javadocs you built to make sure paragraphs have space between them, no junk is in the docs, and the code snippets look good?

**Comment by vivekmuniyandi** [comment]
I just went through all the pages under datamovement and everything is good.

**Comment by vivekmuniyandi** [comment]
@sammefford There is an improper link in BulkExportToJdbc and there are problems with code and formatting in IncrementalLoadFromJdbc and OpticExportListener. Since these are cook book examples, should we really deal with it in the javadoc? If yes, can we do that in 4.0.4 as most of it is formatting issue. Just wanted to confirm this with you.
