### ISSUE TITLE
Functional tests for various types of authentication and authorization scenarios

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#848]
There are lots of combinations with Kerberos, Certificate based authentication and with internal and external authorization and with secure connection(using SSL) and without secure connection. It would be good to have functional tests covering all the scenarios so that we would know if a change is breaking any of the tests.

**Comment by sammefford** [comment]
I think there are also various ways to configure LDAP and Kerberos . . . we should at a minimum map out all the possible combinations.  Then we can decide if we need to test them all.

**Comment by georgeajit** [comment]
Moving to 4.0.5 release.

**Comment by georgeajit** [comment]
Closing this task, since we need to revisit the client based Authentication / Authorization matrix. Currently we have tests DIGEST, DIGEST with SSL, Kerberos, Kerberos with tokens read from file, Certificate based test (test code available, not run continually/daily).

Have opened an internal JIRA task for PMs and Engg. to revisit use cases.
