### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#862]

**Comment by jmakeig** [comment]
Came up in #858

**Comment by ehennum** [comment]
The issue seems to be testing with Java 9 (and, presumably, Java 10 now) and fixing any bugs that show up.

Adding features to exploit the new capabilities of Java 9 and 10 would be in individual RFEs separate from this test item.

**Comment by georgeajit** [comment]
Tested ```develop``` branch of Java Client API with Open JDK 11 on Linux 3 node MarkLogic cluster running 9.0 nightly server builds (Nov 1 st week builds).

Here are results:

1) Had to upgrade ```gradlew``` to use gradle version ```4.10``. Change needed in wrapper properties file.
2) Had to update build.gradle to include  JAXB runtime library to 2.3.0
Used this Gradle dependency in ```marklogic-client-api``` project:
```compile group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '2.3.0' ```
3) Minor QA test code changes needed to account for incorrect classloader usage. Need to use application class loader instead of system class loader in ConnectedRESTQA to load ```test.properties```.
4) ```ml-development-tools``` project had one test failure. Refer to #1032.
5) JaCoCo usage had issues and its plugin usage was commented out. Refer to #1029 , #1030
6) Two tests from ```marklogic-client-api project failed when JDK 11 was used. Refer to #1033 and #1034
7) A couple of QA tests were run and loked fine. Will be running entire suite and updating if failures are found.

**Comment by georgeajit** [comment]
Assigned to Kiran for time being so that right JDK version to be used can be known, after consulting with Product Mangement, DHF teams.

**Comment by ehennum** [comment]
The JDK versions are being clarified as I write.

Based on Ajit's testing and a few fixes that I checked in, I believe develop can compile and run on 8 - 11.

**Comment by georgeajit** [comment]
Have setup Jenkins jobs that handle Java 8, open jdk 9, 10, 11 environments. Had to make gradle (wrapper) changes to handle different Java versions.

**Comment by heelix** [comment]
9 and 10 are end of life.  8 and 11 have long term support options (till
2024).  JDK 12 is now out.  The jump from 8 to 9+ was the tricky one.  Sure
you want to even bother with 9 and 10?  8, 11, and 12 might be better
picks.  (and 12 will have the same short term shelf life).  Come April
16th, the Oracle JDK 8 (and 11, I believe) will require an extended support
contract to get those builds.   AdoptOpenJDK is the free as in beer LST
versions we are going with.

**Comment by ehennum** [comment]
It makes sense that Java shops migrating off 8 are going straight to 11.  Whether most Java shops that are already on 9 or 10 are quickly moving to 11 is less clear.

Our direction for testing is to move to OpenJDK with the premise that it gives us the broadest set of environments.

**Comment by heelix** [comment]
I'm managing the transition at our 350k person shop, and this has been a
tremendous amount of ... fun.
* Oracle requires a commercial license to run on JDK 8 as of January.  JDK
8u201 is likely the last publicly available version.  April 16th is when
the next set of Oracle release hits - for those with an extended support
contract.  (For example, 7u80 is the last public build, 7u211 is the
current build)
* Oracle will have a 'patched' version of 11 for extended support
customers.  For those doing it for free, they must go to 12.  11 Was
identified as an LTS version.
* Adopt OpenJDK has a LTS version of 8 and 11.  (and also a 12) . They
dropped 9 and 10 downloads.
* Oracle dropped 9 and 10 downloads
* RHEL has 8 and 11 OpenJDK LTS Linux versions.  $20 unknown - what does
that mean for Centos users.  RHEL consumers are covered by the license.  9
and 10 appear to be dropped.
* RHEL has 8 and 11 OpenJDK builds for windows, with paid support.
* Amazon is supporting a free as in beer version of 8 and 11.  (Works nice
too)

This was a nice write up of the different blog options out there.
https://blog.joda.org/2018/09/time-to-look-beyond-oracles-jdk.html?m=1

And download links.  If you have JDK 9 and 10 media - hand on to it,
because those binaries will be hard to come by in a few months.

https://access.redhat.com/articles/1299013
https://adoptopenjdk.net/
https://aws.amazon.com/corretto/

**Comment by ehennum** [comment]
Subscribing @aroach337 , who will be interested in the preceding comment.

**Comment by heelix** [comment]
Poking around - the latest release of adoptopenjdk does still show the 9
and 10 versions.  You just get the tar.gz version, so if you are setting up
Linux

# tar -xvf OpenJDK11U-jdk_x64_linux_hotspot_11.0.2_9.tar.gz -C /usr/lib/jvm

# vi /etc/environment
PATH=$PATH:/usr/java/jdk-11.0.2+9/bin:
JAVA_HOME=/usr/java/jdk-11.0.2+9

# update-alternatives --install /usr/bin/java java
/usr/lib/jvm/jdk-11.0.2+9/bin/java 2
# update-alternatives --install /usr/bin/javac javac
/usr/lib/jvm/jdk-11.0.2+9/bin/javac 2

# update-alternatives --config java
# update-alternatives --config javac

For those on a mac, with homebrew (https://brew.sh/)

As an elevated user...
$ brew tap AdoptOpenJDK/openjdk
$ brew cask info adoptopenjdk11
$ brew cask install adoptopenjdk11

You can do 8 with adoptopenjdk8
