### ISSUE TITLE
Java optic API should be able to typecast nodes returned to AnyAtomicTypeExpr

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#866]
For 
```
RowManager rowMgr = client.newRowManager();
PlanBuilder p = rowMgr.newPlanBuilder();
...
...

```
Should be able to cast to numeric type such as

```p.xs.numeric((p.as("nodes", p.xpath("doc", "//latLonPair/lat/"))``` or
```p.fn.number(......)```

**Comment by ehennum** [comment]
Either of the following idioms solve the datatyping issue:

    p.fn.number(p.fn.string(p.fn.head(p.xpath(...))))
    p.xs.numeric(p.fn.string(p.fn.head(p.xpath(...))))

That is, Java strong typing poses two issues for this conversion:

1.  p.xpath() returns a sequence, but fn.number() only takes a single value (like fn.string(), for that matter).
2.  p.xpath() returns nodes, but fn.number() only takes an atomic value (by contrast with fn.string(), which takes an item).

SJS, XQuery, and Node.js don't run into the same strong typing issues because the data types of values aren't enforced statically but, instead, are coerced at runtime where possible.

Aside -- because fn.data() takes a sequence of items, p.fn.data(p.xpath(...)) would be an alternative, but Optic doesn't support fn.data() at present. Even if p.fn.data() were available, to get a single numeric value, you'd still need the full p.fn.number(p.fn.head(p.fn.data(p.xpath(...))))

We could always override the definition of casting functions to take an item sequence as input, but that runs against the Java commitment to strong typing. It might be better to wait for more feedback and encourage the idioms at the top of this comment in the interim.

@sammefford, what's your feeling about this issue?

**Comment by sammefford** [comment]
@ehennum I think I'm on-board, but I'd like to understand better.

@georgeajit could you share a complete code example including sample data and a full Optic Query and desired and actual results?

**Comment by ehennum** [comment]
@sammefford, the datatype issue manifests statically (that is, in the IDE edit buffer or at compile time) rather than at run time.

Some more mulling:  Java provides the cast operator for overriding strong typing.  Because we're enforcing strong typing on the xs.*(), fn.number(), and fn.string() casting functions, we don't provide that escape hatch for building plans. That reasoning argues that we should allow NodeSeq in casting functions.

Unfortunately, that means we need a new marker type that's a union of XsAnyAtomicType and NodeSeq.

**Comment by ehennum** [comment]
The fix relaxes the xs.*(), fn.number(), fn.string(), and sem.iri() casting functions to take an ItemSeqExpr, which is the base type for NodeSeqExpr and thus allows casting functions to be applied to the return value from op.xpath().
