### ISSUE TITLE
Resource leak reported in WriteRowToTableauConsumer constructor

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#894]
* Version of MarkLogic Java Client API: issue 839
* Version of MarkLogic Server : MarkLogic Server Build 10 (Trunk as of 02/21/2018)
* Java version (`java -version`): 1.8 on Eclipse IDE
* OS and version: Windows
* Input: 
Have the following code to get an instance of ```WriteRowToTableauConsumer```
```
tableauWriter = new WriteRowToTableauConsumer(extractedOutFileName)
					.withColumn("id", Type.INTEGER)
					.withColumn("name", Type.UNICODE_STRING)
					.withColumn("date", Type.UNICODE_STRING)
					.withColumn("amount", Type.DOUBLE)
...
...
);
```

* Actual output: Eclipse reports ```Resource leak: '<unassigned Closeable value>' is never closed``` on the first line of the above code.
* Expected output: No resource leaks or a way to close files explicitly.
* Alternatives: None

**Comment by vivekmuniyandi** [comment]
This is not an actual resource leak. It is a false warning. If you break down the code to use without chaining, the warning does go away. It is a memory leak if withColumn returns a new instance instead of 'this' which in this case returns 'this' only. We close the Consumer in the ExtractViaTemplateListener's close method which is closed automatically by QueryBatcher - #891
